# Generated by Django 6.1.1 on 2026-09-28 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def approve_existing_users(apps, schema_editor):
    # Accounts that existed before approval was introduced keep working: only new sign-ups start as pending.
    User = apps.get_model('accounts', 'User')
    User.objects.update(approval_status='APPROVED', approved_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Whether an administrator has approved this account', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTRATION', 'Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('ROLE_CHANGE', 'Role Change'), ('ACCOUNT_DEACTIVATION', 'Account Deactivation'), ('ACCOUNT_ACTIVATION', 'Account Activation'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('REGISTER', 'Email verification'), ('LOGIN', 'Sign-in'), ('PASSWORD_RESET', 'Password reset')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='accounts_em_user_id_dc4b02_idx')],
            },
        ),
        migrations.RunPython(approve_existing_users, migrations.RunPython.noop),
    ]
