# Generated by Django 6.1.1 on 2026-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_approval_and_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SCHOLARSHIP_MANAGER', 'Scholarship Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('COUNSELLOR', 'Counsellor'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student')], default='STUDENT', help_text='User role in the system', max_length=50),
        ),
    ]
