# Generated by Django 6.1.1 on 2026-10-02 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTRATION', 'Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('ROLE_CHANGE', 'Role Change'), ('ACCOUNT_DEACTIVATION', 'Account Deactivation'), ('ACCOUNT_ACTIVATION', 'Account Activation'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected'), ('TWO_STEP_ON', 'Two-step sign-in turned on'), ('TWO_STEP_OFF', 'Two-step sign-in turned off'), ('RECOVERY_CODES', 'New recovery codes'), ('DEVICE_SIGNED_OUT', 'Device signed out')], max_length=50),
        ),
        migrations.CreateModel(
            name='AuthenticatorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(help_text='Base32 secret shared with the app.', max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Set once the user has entered a first code.', null=True)),
                ('last_step', models.BigIntegerField(default=0, help_text='The last 30-second step used, so a code works only once.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(blank=True, help_text='How they signed in: email code, authenticator, Google…', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='accounts_us_user_id_9fbea3_idx')],
            },
        ),
    ]
