# Generated by Django 6.1.1 on 2026-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_two_step_and_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SCHOLARSHIP_MANAGER', 'Scholarship Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('COUNSELLOR', 'Counsellor'), ('INSTRUCTOR', 'Instructor'), ('TEAM_MEMBER', 'Team member'), ('STUDENT', 'Student')], default='STUDENT', help_text='User role in the system', max_length=50),
        ),
    ]
