# Generated by Django 6.1.1 on 2026-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='service_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portalevent',
            name='kind',
            field=models.CharField(choices=[('viewed', 'Viewed a scholarship'), ('opened_link', 'Opened an official website'), ('saved', 'Saved a scholarship'), ('unsaved', 'Removed a saved scholarship'), ('application_started', 'Started an application'), ('stage_changed', 'Application stage changed'), ('document_done', 'Ticked off a document'), ('goals_updated', 'Updated study goals'), ('service_requested', 'Asked ADRAM to apply')], max_length=30),
        ),
    ]
