# Generated by Django 6.1.1 on 2026-09-28 08:02

import django.core.files.storage
import django.db.models.deletion
import pathlib
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_service_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=portal.models.document_upload_to),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original file name, for display.', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portalevent',
            name='kind',
            field=models.CharField(choices=[('viewed', 'Viewed a scholarship'), ('opened_link', 'Opened an official website'), ('saved', 'Saved a scholarship'), ('unsaved', 'Removed a saved scholarship'), ('application_started', 'Started an application'), ('stage_changed', 'Application stage changed'), ('document_done', 'Ticked off a document'), ('goals_updated', 'Updated study goals'), ('service_requested', 'Asked ADRAM to apply'), ('service_decision', 'ADRAM updated the application request'), ('terms_accepted', 'Accepted the terms and conditions'), ('document_uploaded', 'Uploaded a document'), ('payment_submitted', 'Submitted a payment receipt')], max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afrimoney_number', models.CharField(blank=True, max_length=30)),
                ('afrimoney_name', models.CharField(blank=True, max_length=100, verbose_name='Afrimoney account name')),
                ('orange_money_number', models.CharField(blank=True, max_length=30)),
                ('orange_money_name', models.CharField(blank=True, max_length=100, verbose_name='Orange Money account name')),
                ('instructions', models.TextField(blank=True, help_text='How to pay, shown on the payment page.')),
                ('terms', models.TextField(blank=True, verbose_name='terms and conditions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment settings',
                'verbose_name_plural': 'payment settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Waiting for ADRAM to review'), ('approved', 'Approved: read the guidelines and pay'), ('declined', 'Declined'), ('payment_submitted', 'Payment submitted: being checked'), ('payment_rejected', 'Payment not confirmed: upload again'), ('paid', 'Paid: ADRAM is working on the application')], default='requested', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount (NLe)')),
                ('guidelines', models.TextField(blank=True, help_text='Your guidelines for this student, shown once approved.')),
                ('decision_note', models.TextField(blank=True, help_text='Why a request was declined or a payment was not confirmed.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('afrimoney', 'Afrimoney'), ('orange_money', 'Orange Money')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=portal.models.receipt_upload_to)),
                ('receipt_name', models.CharField(blank=True, max_length=200)),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='portal.application')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
