# Generated by Django 6.1.1 on 2026-09-28 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_default_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='resubmitted',
            field=models.BooleanField(default=False, help_text='Uploaded again after being returned.'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='review_note',
            field=models.CharField(blank=True, help_text='What the student should change.', max_length=500),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='review_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('returned', 'Returned for changes')], max_length=10),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='review_tag',
            field=models.CharField(blank=True, choices=[('unreadable', 'Unclear / unreadable'), ('wrong_document', 'Wrong document'), ('expired', 'Expired'), ('incomplete', 'Incomplete / pages missing'), ('needs_certification', 'Needs certification or stamp'), ('name_mismatch', 'Name doesn’t match'), ('needs_translation', 'Needs an English translation'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portalevent',
            name='kind',
            field=models.CharField(choices=[('viewed', 'Viewed a scholarship'), ('opened_link', 'Opened an official website'), ('saved', 'Saved a scholarship'), ('unsaved', 'Removed a saved scholarship'), ('application_started', 'Started an application'), ('stage_changed', 'Application stage changed'), ('document_done', 'Ticked off a document'), ('goals_updated', 'Updated study goals'), ('service_requested', 'Asked ADRAM to apply'), ('service_decision', 'ADRAM updated the application request'), ('terms_accepted', 'Accepted the terms and conditions'), ('document_uploaded', 'Uploaded a document'), ('payment_submitted', 'Submitted a payment receipt'), ('document_reviewed', 'ADRAM reviewed a document'), ('milestone_updated', 'ADRAM updated the progress timeline')], max_length=30),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='todo', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='target date')),
                ('note', models.CharField(blank=True, help_text='Shown to the student.', max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portal.application')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
