# Generated by Django 6.1.1 on 2026-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_interview_and_result_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='advice_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
