# Generated by Django 6.1.1 on 2026-09-28 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_timeline_and_service'),
        ('portal', '0010_advice_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalevent',
            name='kind',
            field=models.CharField(choices=[('viewed', 'Viewed a scholarship'), ('opened_link', 'Opened an official website'), ('saved', 'Saved a scholarship'), ('unsaved', 'Removed a saved scholarship'), ('application_started', 'Started an application'), ('stage_changed', 'Application stage changed'), ('document_done', 'Ticked off a document'), ('goals_updated', 'Updated study goals'), ('service_requested', 'Asked ADRAM to apply'), ('service_decision', 'ADRAM updated the application request'), ('terms_accepted', 'Accepted the terms and conditions'), ('document_uploaded', 'Uploaded a document'), ('payment_submitted', 'Submitted a payment receipt'), ('document_reviewed', 'ADRAM reviewed a document'), ('milestone_updated', 'ADRAM updated the progress timeline'), ('training', 'Training programme')], max_length=30),
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Enrollment requested'), ('active', 'Enrolled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Message from ADRAM, shown to the student (class times, what to bring…).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catalog.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_training_enrollment')],
            },
        ),
    ]
