# Generated by Django 6.1.1 on 2026-09-29 00:01

import django.core.files.storage
import pathlib
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=portal.models.message_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('file', 'File'), ('image', 'Image'), ('audio', 'Voice message')], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Length of a voice message, in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
