# Generated by Django 6.1.1 on 2026-09-30 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingenrollment',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='status',
            field=models.CharField(choices=[('requested', 'Enrollment requested'), ('active', 'Enrolled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Not accepted')], default='requested', max_length=15),
        ),
    ]
