# Generated by Django 6.1.1 on 2026-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_enrollment_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='afrimoney_steps',
            field=models.TextField(blank=True, help_text='Step-by-step for Afrimoney, one step per line (optional).'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='card_label',
            field=models.CharField(blank=True, default='Visa / Mastercard', max_length=60),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='card_link',
            field=models.URLField(blank=True, help_text='A hosted card-payment page (from your bank or payment service). Students pay there, then upload the confirmation.', max_length=500, verbose_name='card payment link'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='card_steps',
            field=models.TextField(blank=True, help_text='How to pay by card, one step per line (e.g. at the ADRAM office).'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='orange_money_steps',
            field=models.TextField(blank=True, help_text='Step-by-step for Orange Money, one step per line (optional).'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payer',
            field=models.CharField(blank=True, help_text='The number paid from, or the name on the card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('afrimoney', 'Afrimoney'), ('orange_money', 'Orange Money'), ('card', 'Card')], max_length=20),
        ),
    ]
