# Generated by Django 6.1.1 on 2026-10-03 07:11

import django.core.files.storage
import django.db.models.deletion
import pathlib
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='allow_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='allow_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='method',
            field=models.CharField(choices=[('online', 'Filled in online'), ('upload', 'Scanned paper form')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntakeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=portal.models.intake_upload_to)),
                ('file_name', models.CharField(max_length=200)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portal.intakesubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
