# Generated by Django 6.1.1 on 2026-10-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_application_form_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesubmission',
            name='approved_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='approved_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='approved_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='flagged_fields',
            field=models.JSONField(blank=True, default=list, help_text='Questions ADRAM asked the student to check.'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Not submitted yet'), ('submitted', 'Submitted'), ('returned', 'Returned for changes'), ('reviewed', 'Approved by ADRAM')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_signature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
