# Generated by Django 6.1.1 on 2026-10-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_application_form_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Scholarship Application and Success-Based Service Agreement', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='International Scholarship Consultancy & Student Placement Services', max_length=200)),
                ('company_name', models.CharField(default='ADRAM TECHNOLOGIES', max_length=150)),
                ('company_description', models.TextField(blank=True, max_length=600)),
                ('company_address', models.CharField(blank=True, max_length=300)),
                ('representative_name', models.CharField(blank=True, max_length=120)),
                ('representative_position', models.CharField(blank=True, max_length=120)),
                ('company_signature', models.TextField(blank=True)),
                ('company_stamp', models.TextField(blank=True)),
                ('clauses', models.JSONField(blank=True, default=list)),
                ('default_fee', models.CharField(blank=True, help_text='e.g. NLe 15,000. Can be changed for each student.', max_length=80)),
                ('auto_issue', models.BooleanField(default=True, help_text='Send the agreement automatically when a result is marked Accepted.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service agreement template',
                'verbose_name_plural': 'service agreement template',
            },
        ),
        migrations.CreateModel(
            name='StudentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting for the student to sign'), ('signed', 'Signed'), ('void', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('content', models.JSONField(default=dict)),
                ('fee', models.CharField(blank=True, max_length=80)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('student_details', models.JSONField(blank=True, default=dict)),
                ('student_signature', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.CharField(blank=True, max_length=300)),
                ('fingerprint', models.CharField(blank=True, help_text='SHA-256 of exactly what the student signed.', max_length=64)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='portal.application')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
