# Generated by Django 6.1.1 on 2026-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_service_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementtemplate',
            name='auto_issue',
            field=models.BooleanField(default=True, help_text='Send the agreement automatically with the application form (when the payment is confirmed).'),
        ),
    ]
