# Generated by Django 6.1.1 on 2026-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_agreement_auto_issue_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='require_read',
            field=models.BooleanField(default=True, help_text='The student must scroll to the end before they can sign.'),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='signature_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='student_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='wording',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentagreement',
            name='signature_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
