# Generated by Django 6.1.1 on 2026-10-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_agreement_paper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Empty = the whole ADRAM team.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user', 'member'), name='one_thread_per_member'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', True)), fields=('user',), name='one_team_thread_per_person'),
        ),
    ]
