# Generated by Django 6.1.1 on 2026-09-28 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in the page address; changing it breaks old links.', max_length=80, unique=True)),
                ('summary', models.TextField()),
                ('is_published', models.BooleanField(default=False, help_text='Only published items appear on the website.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are listed first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('ai', 'ai'), ('terminal', 'terminal'), ('web', 'web'), ('architecture', 'architecture'), ('mobile', 'mobile'), ('briefcase', 'briefcase'), ('software', 'software'), ('network', 'network'), ('laptop', 'laptop'), ('server', 'server'), ('shield', 'shield'), ('design', 'design'), ('build', 'build'), ('layers', 'layers'), ('innovation', 'innovation'), ('classroom', 'classroom'), ('certificate', 'certificate'), ('consult', 'consult'), ('transform', 'transform'), ('growth', 'growth'), ('finance', 'finance'), ('people', 'people'), ('community', 'community'), ('graduate', 'graduate'), ('flask', 'flask'), ('globe', 'globe')], default='laptop', max_length=30)),
                ('topics', models.JSONField(default=list, help_text='Short topic tags shown on the card.')),
                ('duration', models.CharField(blank=True, help_text='e.g. “8 weeks, evenings”', max_length=100)),
                ('fee', models.CharField(blank=True, help_text='e.g. “Le 2,500” — leave blank to ask people to enquire.', max_length=100)),
                ('next_intake', models.DateField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in the page address; changing it breaks old links.', max_length=80, unique=True)),
                ('summary', models.TextField()),
                ('is_published', models.BooleanField(default=False, help_text='Only published items appear on the website.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are listed first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('gb', 'United Kingdom'), ('us', 'United States'), ('ca', 'Canada'), ('de', 'Germany'), ('eu', 'Europe (multi-country)'), ('nl', 'Netherlands'), ('cn', 'China'), ('tr', 'Türkiye'), ('in', 'India'), ('africa', 'Africa & worldwide')], max_length=10, verbose_name='destination')),
                ('levels', models.JSONField(default=list, help_text='Any of: Undergraduate, Masters, PhD')),
                ('funding', models.CharField(choices=[('full', 'Fully funded'), ('partial', 'Partial funding')], default='full', max_length=10)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('fields', models.CharField(blank=True, max_length=255, verbose_name='fields of study')),
                ('application_window', models.CharField(blank=True, help_text='e.g. “Applications typically open in August.”', max_length=255)),
                ('deadline', models.DateField(blank=True, help_text='Next confirmed closing date, if known.', null=True)),
                ('covers', models.JSONField(default=list, help_text='What the award pays for, one item per line.')),
                ('eligibility', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list, help_text='How to apply, in order.')),
                ('url', models.URLField(max_length=500, verbose_name='official website')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
