# Generated by Django 6.1.1 on 2026-09-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='hide_official_link',
            field=models.BooleanField(default=False, help_text='Don’t show the provider’s website; students go through ADRAM instead.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Visitors see the summary; eligibility, steps and the official link need a signed-in account.', verbose_name='sign-in to view details'),
        ),
    ]
