# Generated by Django 6.1.1 on 2026-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_scholarship_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='service_cutoff',
            field=models.DateField(blank=True, help_text='Date the student must send everything by.', null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='service_enabled',
            field=models.BooleanField(default=True, verbose_name='ADRAM application service'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='service_fee',
            field=models.CharField(blank=True, help_text='e.g. “Free” or “NLe 1,500”.', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='service_includes',
            field=models.JSONField(blank=True, default=list, help_text='What ADRAM does for the student.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='service_note',
            field=models.TextField(blank=True, help_text='Instructions shown to interested students.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='service_requirements',
            field=models.JSONField(blank=True, default=list, help_text='What the student must send ADRAM; becomes their documents checklist.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
