# Generated by Django 6.1.1 on 2026-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_more_training_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.JSONField(blank=True, default=list, help_text='Who this course is for.'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='The full description shown on the course page. A blank line starts a new paragraph.'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_mode',
            field=models.CharField(choices=[('open', 'Open: students get instant access'), ('approval', 'By approval: ADRAM confirms each place')], default='approval', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_photo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_points',
            field=models.JSONField(blank=True, default=list, help_text='“What you’ll learn” bullet points.'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('all', 'All levels'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='all', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='A YouTube or Vimeo link to a short trailer.', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='What students need before they start.'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='The course picture (an uploaded image or a website photo).', max_length=300),
        ),
    ]
