# Generated by Django 6.1.1 on 2026-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_course_audience_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Students pay this to enrol. Leave empty (or 0) for a free course.', max_digits=12, null=True, verbose_name='price (NLe)'),
        ),
    ]
