# Generated by Django 6.1.1 on 2026-09-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_course_status_from_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='format_label',
            field=models.CharField(blank=True, default='Course', help_text='The type shown on the card: Course, Bootcamp, Workshop…', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='highlight',
            field=models.CharField(blank=True, choices=[('', 'None'), ('bestseller', 'Bestseller'), ('highest_rated', 'Highest rated'), ('hot_new', 'Hot & new'), ('new', 'New')], default='', help_text='A label on the card, e.g. Bestseller.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Shows the "Premium" badge on the course card.'),
        ),
    ]
