# Generated by Django 6.1.1 on 2026-09-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_course_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='caption_languages',
            field=models.JSONField(blank=True, default=list, help_text='Subtitle languages shown under the title, e.g. “French [Auto]”.'),
        ),
        migrations.AddField(
            model_name='course',
            name='feature',
            field=models.JSONField(blank=True, default=dict, help_text='A highlighted box on the course page: {title, text, image, link_label, link_url}.'),
        ),
        migrations.AddField(
            model_name='course',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text='Extra lines for “This course includes”, e.g. “Access on mobile and TV”.'),
        ),
        migrations.AddField(
            model_name='course',
            name='premium_note',
            field=models.CharField(blank=True, help_text='Text in the Premium bar under the title (Premium courses only).', max_length=300),
        ),
    ]
