# Generated by Django 6.1.1 on 2026-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_course_page_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_downloads',
            field=models.BooleanField(default=True, help_text='Enrolled students can download the lesson materials.'),
        ),
        migrations.AddField(
            model_name='course',
            name='allow_video_downloads',
            field=models.BooleanField(default=False, help_text='Also let them download uploaded lesson videos (large files).'),
        ),
    ]
