# Generated by Django 6.1.1 on 2026-10-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_course_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shown to students, e.g. "Easter sale".', max_length=80)),
                ('percent_off', models.PositiveSmallIntegerField(help_text='1 to 90.')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Leave empty for every paid course.', related_name='flash_sales', to='catalog.course')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
