# Generated by Django 6.1.1 on 2026-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('summary', models.CharField(help_text='One or two sentences, shown on the project card.', max_length=320)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Shown large at the top of the Projects page.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('client', models.CharField(blank=True, max_length=150)),
                ('client_logo', models.CharField(blank=True, max_length=500)),
                ('sector', models.CharField(blank=True, help_text='e.g. Education, Health, NGO, Government, Retail.', max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(blank=True, help_text='The id of the ADRAM service it belongs to, e.g. web-development.', max_length=60)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 months.', max_length=60)),
                ('live_url', models.URLField(blank=True, max_length=300)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('challenge', models.TextField(blank=True, max_length=8000)),
                ('solution', models.TextField(blank=True, max_length=8000)),
                ('outcome', models.TextField(blank=True, max_length=8000)),
                ('results', models.JSONField(blank=True, default=list)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('quote', models.TextField(blank=True, max_length=800)),
                ('quote_author', models.CharField(blank=True, max_length=120)),
                ('quote_role', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-completed_on', '-created_at'],
            },
        ),
    ]
