"""
Django settings for ADRAM Backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys

from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# All secrets and environment-specific values come from backend/.env
# (copy .env.example to .env). See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'api',
    'accounts',
    'contact',
    'catalog',
    'cms',
    'lms',
    'portal',
    'newsletter',
    'blog',
    'partners',
    'projects',
    'team.apps.TeamConfig',
    'chatbot',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',  # ETag on GET responses: apps can ask "changed?" and get a quick 304
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'cms.lock.SiteLockMiddleware',  # Admin → Lock website: refuses visitors' changes while locked
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['ETag']  # so web and app clients can send it back as If-None-Match

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# SQLite by default (development). Set DB_ENGINE=django.db.backends.postgresql
# and the DB_* values in .env to use PostgreSQL in production.
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User uploads (e.g. profile pictures)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Serve the built website (frontend/dist) from Django too, with the edited search and link-preview tags.
# Off by default: in development Vite serves the site and the API root shows the API docs.
# Largest lesson video an administrator can upload, in megabytes (bigger ones belong on YouTube or Vimeo)
LMS_MAX_VIDEO_MB = config('LMS_MAX_VIDEO_MB', default=1500, cast=int)
SERVE_FRONTEND = config('SERVE_FRONTEND', default=False, cast=bool)
FRONTEND_DIST = config('FRONTEND_DIST', default=str(BASE_DIR.parent / 'frontend' / 'dist'))
# Payment receipts and application documents: never served directly, only through the portal API.
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== CUSTOM USER MODEL ==========
AUTH_USER_MODEL = 'accounts.User'

# ========== JWT AUTHENTICATION ==========
# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.SessionJWTAuthentication',  # JWT + signed-out devices stop at once
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': ['api.throttling.AnonRate'],
    'EXCEPTION_HANDLER': 'api.throttling.exception_handler',
}

# ========== REQUEST LIMITS (api/throttling.py) ==========
# Per network address. Generous, because many people share one mobile-network address.
# Off while the test suite runs (it sends thousands of requests from one address in seconds).
TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'
API_THROTTLING = config('API_THROTTLING', default=not TESTING, cast=bool)
API_RATES = {
    'anon': config('RATE_ANON', default='1500/min'),       # any visitor who isn't signed in
    'auth': config('RATE_AUTH', default='60/min'),        # sign-in and code checks
    'signup': config('RATE_SIGNUP', default='40/hour'),   # new accounts
    'email': config('RATE_EMAIL', default='40/hour'),     # requests that send someone an email
    'forms': config('RATE_FORMS', default='30/hour'),     # contact, newsletter and partner forms
    'codes': config('RATE_CODES', default='60/min'),      # gift, certificate and group codes
}
# Failed passwords for one email from one address before sign-in pauses for LOGIN_LOCKOUT_MINUTES
LOGIN_MAX_FAILURES = config('LOGIN_MAX_FAILURES', default=10, cast=int)
LOGIN_LOCKOUT_MINUTES = config('LOGIN_LOCKOUT_MINUTES', default=15, cast=int)

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# ============================================
# SECURITY SETTINGS
# ============================================

# Session Security (secure cookies are switched on automatically when DEBUG is off)
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser closes

# CSRF Security
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Security Headers
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # other sites see only the domain, never the page or its ?query
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'  # keeps sign-in pop-ups (OAuth) working

# HTTPS (production). Each can be set in .env; with DEBUG off, HTTP is redirected to HTTPS by default.
# Behind a proxy that ends HTTPS (nginx, a load balancer, cPanel), also set SECURE_PROXY_SSL_HEADER=true.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
if config('SECURE_PROXY_SSL_HEADER', default=False, cast=bool):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# HSTS tells browsers to use HTTPS only. Turn it on (e.g. 31536000 = 1 year) once HTTPS works on every subdomain.
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
# The website's own address(es) for form posts over HTTPS, e.g. https://adramtechnologies.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
# The interactive API docs (Swagger/ReDoc) are open in development; in production only staff can see them.
API_DOCS_PUBLIC = config('API_DOCS_PUBLIC', default=DEBUG, cast=bool)


# ========== EMAIL CONFIGURATION ==========
# Console backend prints emails to the terminal; use smtp.EmailBackend in production.
# Email codes per person per hour: no limit in development; 10 in production (stops code-guessing with endless
# new codes, and floods of emails). Set OTP_MAX_CODES_PER_HOUR in .env to change it (0 = no limit).
OTP_MAX_CODES_PER_HOUR = config('OTP_MAX_CODES_PER_HOUR', default=0 if DEBUG else 10, cast=int) or None

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@adramtechnologies.com')
# Where contact-form notifications are sent
CONTACT_NOTIFY_EMAIL = config('CONTACT_NOTIFY_EMAIL', default='adramtechnologies@gmail.com')

# Voice and video calls (WebRTC). STUN lets browsers find each other; on strict networks (some mobile
# data and office firewalls) calls also need a TURN relay. Add one as JSON in the environment, e.g.
# WEBRTC_ICE_SERVERS=[{"urls":"stun:stun.l.google.com:19302"},{"urls":"turn:turn.example.com:3478","username":"u","credential":"p"}]
import json as _json  # noqa: E402
WEBRTC_ICE_SERVERS = _json.loads(config(
    'WEBRTC_ICE_SERVERS',
    default='[{"urls": ["stun:stun.l.google.com:19302", "stun:stun1.l.google.com:19302"]}]',
))

# ========== LOGGING CONFIGURATION ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': config('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)


# ========== URL CONFIGURATION ==========
APPEND_SLASH = True


# ========== SOCIAL SIGN-IN (OAuth) ==========
# Where the browser is sent after sign-in, and the public address of this API (used to build the
# redirect URI registered with each provider: {BACKEND_URL}/api/v1/auth/oauth/<provider>/callback/).
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')
BACKEND_URL = config('BACKEND_URL', default='http://127.0.0.1:8000')

# Leave a pair empty to switch that provider off.
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')
FACEBOOK_CLIENT_ID = config('FACEBOOK_CLIENT_ID', default='')
FACEBOOK_CLIENT_SECRET = config('FACEBOOK_CLIENT_SECRET', default='')
GITHUB_CLIENT_ID = config('GITHUB_CLIENT_ID', default='')
GITHUB_CLIENT_SECRET = config('GITHUB_CLIENT_SECRET', default='')

# ========== WEBSITE ASSISTANT (chatbot) ==========
# A key from https://console.anthropic.com switches the chat assistant on (see chatbot/ai.py). Empty = it explains it's not set up.
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
