# Generated by Django 6.1.1 on 2026-09-29 17:43

import django.core.files.storage
import django.db.models.deletion
import lms.models
import pathlib
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_course_currency_course_discount_price_course_faqs_and_more'),
        ('lms', '0003_announcement_coupon_coursepayment_thread_reply_and_more'),
        ('portal', '0014_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('30'), help_text='The platform keeps this share of each sale; instructors earn the rest.', max_digits=5)),
                ('certificate_signer_name', models.CharField(blank=True, max_length=120)),
                ('certificate_signer_title', models.CharField(blank=True, default='Director of Training', max_length=120)),
                ('certificate_signature', models.CharField(blank=True, help_text='An uploaded image of the signature.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LMS settings',
                'verbose_name_plural': 'LMS settings',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoke_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to work on every course.', related_name='coupon_set', to='catalog.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The basket must be worth at least this.', max_digits=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='How many orders one student may use it on (0 = no limit).'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='allow_resubmit',
            field=models.BooleanField(default=True, help_text='Assignment: students may hand in again until it is approved.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=lms.models.document_upload_to),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Needed to complete the course and earn the certificate.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited attempts.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_points',
            field=models.PositiveSmallIntegerField(default=100, help_text='Assignment: the grade is out of this.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='questions_per_attempt',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ask a random selection of this many questions; 0 = all.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='show_answers',
            field=models.BooleanField(default=True, help_text='Show the correct answers after each attempt.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='shuffle_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = no time limit.'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on this lesson.'),
        ),
        migrations.AddField(
            model_name='progress',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0, help_text='The furthest point of the video reached.'),
        ),
        migrations.AddField(
            model_name='question',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text='Short answer: the answers marked right (case and spacing ignored).'),
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('single', 'Multiple choice'), ('multiple', 'Multiple answers'), ('true_false', 'True / false'), ('short', 'Short answer')], default='single', max_length=12),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='choice_order',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question_ids',
            field=models.JSONField(blank=True, default=list, help_text='The questions asked, in the order shown.'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='submitted', max_length=12),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_instructor_answer',
            field=models.BooleanField(default=False, help_text='Marked by the instructor as the answer.'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden by a moderator: not shown or counted.'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Reading'), ('document', 'Document'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Written by the instructor or an administrator.'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('target_label', models.CharField(blank=True, max_length=250)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_seconds', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enrollment', 'Enrollment'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('course_approved', 'Course approved'), ('course_rejected', 'Course rejected'), ('course_review', 'Course review'), ('new_lecture', 'New lecture'), ('announcement', 'Announcement'), ('quiz_result', 'Quiz result'), ('assignment_submitted', 'Assignment submitted'), ('assignment_graded', 'Assignment graded'), ('certificate', 'Certificate'), ('coupon', 'Coupon'), ('question', 'Question'), ('answer', 'Answer'), ('review', 'Review'), ('report', 'Report'), ('refund', 'Refund'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, help_text='Where clicking it goes on the website.', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for payment'), ('processing', 'Payment being checked'), ('successful', 'Paid'), ('failed', 'Payment failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('currency', models.CharField(default='NLe', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.CharField(default='manual', help_text='The payment provider handling this order.', max_length=30)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=lms.models.receipt_upload_to)),
                ('receipt_name', models.CharField(blank=True, max_length=200)),
                ('decision_note', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='lms.coupon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_orders', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('instructor_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True, max_length=5000)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list, help_text='Topics the student wants to learn; used for recommendations.')),
                ('website', models.URLField(blank=True, max_length=300)),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('twitter', models.URLField(blank=True, max_length=300)),
                ('youtube', models.URLField(blank=True, max_length=300)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('facebook', models.URLField(blank=True, max_length=300)),
                ('payout_details', models.TextField(blank=True, help_text='Private: how the instructor wants to be paid.', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('course', 'Course'), ('review', 'Review'), ('thread', 'Question'), ('reply', 'Answer'), ('other', 'Other')], max_length=10)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=250)),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('abuse', 'Harassment or hate'), ('inappropriate', 'Inappropriate content'), ('copyright', 'Copyright problem'), ('misleading', 'Misleading or wrong'), ('other', 'Something else')], default='other', max_length=20)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=10)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=20000)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=lms.models.submission_upload_to)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Waiting for grading'), ('approved', 'Approved'), ('rejected', 'Needs more work')], default='submitted', max_length=10)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, max_length=5000)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portal.trainingenrollment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.lesson')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lms.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='catalog.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='one_cart_entry')],
            },
        ),
        migrations.CreateModel(
            name='CourseViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_days', to='catalog.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'date'), name='one_view_row_per_day')],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='one_recent_view')],
            },
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lms.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reply', 'user'), name='one_like_per_reply')],
            },
        ),
    ]
