# Generated by Django 6.1.1 on 2026-09-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_orders_from_course_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='course',
        ),
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
