# Generated by Django 6.1.1 on 2026-09-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_remove_course_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='resource',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
