# Generated by Django 6.1.1 on 2026-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_resource_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer',
            field=models.CharField(blank=True, help_text='The number paid from, or the name on the card.', max_length=100),
        ),
    ]
