# Generated by Django 6.1.1 on 2026-10-02 06:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_search_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lmssettings',
            name='min_withdrawal',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='The smallest withdrawal an instructor can ask for.', max_digits=12),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='payout_hold_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Days a sale is held before its earnings can be withdrawn (refund window).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=60, verbose_name='tax ID (TIN / NIN)'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('orange_money', 'Orange Money'), ('afrimoney', 'Afrimoney'), ('bank', 'Bank transfer'), ('other', 'Other')], max_length=20)),
                ('account', models.CharField(help_text='Phone number or bank account number.', max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=12)),
                ('admin_note', models.CharField(blank=True, help_text='Why it was rejected, or a note with the payment.', max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('payout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='lms.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
