# Generated by Django 6.1.1 on 2026-10-02 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def lessons_from_history(apps, schema_editor):
    """Past days: the lessons finished each day (minutes weren't recorded per day before, so they start at 0)."""
    from collections import Counter
    Progress = apps.get_model('lms', 'Progress')
    LearningDay = apps.get_model('lms', 'LearningDay')
    counts = Counter()
    for user_id, done in Progress.objects.filter(completed_at__isnull=False).values_list('enrollment__student_id', 'completed_at'):
        counts[(user_id, done.date())] += 1
    LearningDay.objects.bulk_create([LearningDay(user_id=u, date=d, lessons_completed=n) for (u, d), n in counts.items()])


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_withdrawals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_minutes', models.PositiveSmallIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='one_learning_day')],
            },
        ),
        migrations.RunPython(lessons_from_history, migrations.RunPython.noop),
    ]
