# Generated by Django 6.1.1 on 2026-10-02 11:27

import django.core.files.storage
import django.db.models.deletion
import lms.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_question_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='Assignment: the deadline for everyone.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='due_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Assignment: or, due this many days after the student enrols (0 = not used).'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='late_penalty_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='Penalty: the share of the grade taken off late work.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='late_policy',
            field=models.CharField(choices=[('accept', 'Accept late work (marked late)'), ('penalty', 'Accept late work with a penalty'), ('closed', 'Close at the deadline')], default='accept', max_length=8),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_files',
            field=models.PositiveSmallIntegerField(default=1, help_text='Assignment: how many files may be handed in at once.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rubric',
            field=models.JSONField(blank=True, default=list, help_text='Assignment: grading criteria [{title, description, points}].'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='penalty_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Taken off the grade because the work was late.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='raw_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The grade before any late penalty.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=list, help_text='Points given for each rubric criterion, in order.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('course_approved', 'Course approved'), ('course_rejected', 'Course rejected'), ('course_review', 'Course review'), ('new_lecture', 'New lecture'), ('announcement', 'Announcement'), ('quiz_result', 'Quiz result'), ('assignment_submitted', 'Assignment submitted'), ('assignment_graded', 'Assignment graded'), ('assignment_due', 'Assignment due'), ('certificate', 'Certificate'), ('coupon', 'Coupon'), ('question', 'Question'), ('answer', 'Answer'), ('review', 'Review'), ('report', 'Report'), ('refund', 'Refund'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=lms.models.submission_upload_to)),
                ('filename', models.CharField(max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lms.submission')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
