# Generated by Django 6.1.1 on 2026-10-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_flash_sales'),
        ('lms', '0013_assignment_deadlines_rubrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('layout', models.CharField(choices=[('classic', 'Classic (framed)'), ('modern', 'Modern (coloured band)'), ('minimal', 'Minimal')], default='classic', max_length=10)),
                ('accent_color', models.CharField(default='#1d4ed8', help_text='A colour like #1d4ed8.', max_length=7)),
                ('title', models.CharField(default='Certificate of completion', max_length=80)),
                ('heading', models.CharField(blank=True, default='Congratulations', max_length=80)),
                ('lead', models.CharField(default='has successfully completed the course', max_length=160)),
                ('footer_note', models.CharField(blank=True, help_text='A line under the signatures, e.g. an accreditation.', max_length=200)),
                ('show_hours', models.BooleanField(default=True)),
                ('show_instructor', models.BooleanField(default=True)),
                ('show_qr', models.BooleanField(default=True, help_text='A QR code that opens the verification page.')),
                ('signer_name', models.CharField(blank=True, help_text='Leave empty to use the LMS settings.', max_length=120)),
                ('signer_title', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='certificate_templates', to='catalog.course')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The look it was issued with (none: the built-in design).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='lms.certificatetemplate'),
        ),
    ]
