# Generated by Django 6.1.1 on 2026-10-02 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_certificate_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Accepted by the student who asked: it solved their question.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned by the instructor: shown first.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='position_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='The moment in the lesson video it is about.', null=True),
        ),
        migrations.CreateModel(
            name='ThreadVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='lms.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('thread', 'user'), name='one_vote_per_thread')],
            },
        ),
    ]
