# Generated by Django 6.1.1 on 2026-10-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_community_votes_pins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseviewday',
            name='cart_adds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseviewday',
            name='checkouts',
            field=models.PositiveIntegerField(default=0, help_text='Orders placed that include the course (paid or not yet).'),
        ),
        migrations.AddField(
            model_name='courseviewday',
            name='wishlist_adds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('course_approved', 'Course approved'), ('course_rejected', 'Course rejected'), ('course_review', 'Course review'), ('new_lecture', 'New lecture'), ('announcement', 'Announcement'), ('quiz_result', 'Quiz result'), ('assignment_submitted', 'Assignment submitted'), ('assignment_graded', 'Assignment graded'), ('assignment_due', 'Assignment due'), ('certificate', 'Certificate'), ('coupon', 'Coupon'), ('question', 'Question'), ('answer', 'Answer'), ('review', 'Review'), ('report', 'Report'), ('refund', 'Refund'), ('new_course', 'New course'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.CreateModel(
            name='InstructorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'instructor'), name='follow_once')],
            },
        ),
    ]
