# Generated by Django 6.1.1 on 2026-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_followers_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='Instructors: a YouTube or Vimeo video introducing themselves.', max_length=500),
        ),
    ]
