# Generated by Django 6.1.1 on 2026-10-02 13:28

import django.db.models.deletion
import lms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_bundles_gifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='A personal code (e.g. a referral reward): only this person can use it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='referral_friend_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='Welcome discount for the friend who joins (%).'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='referral_reward_percent',
            field=models.PositiveSmallIntegerField(default=15, help_text='Reward for the student who invited them (%).'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='referral_valid_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='How long the referral codes can be used.'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='referrals_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('reward_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.coupon')),
                ('rewarded_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.order')),
                ('welcome_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.coupon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=lms.models.new_referral_code, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
