# Generated by Django 6.1.1 on 2026-10-02 13:50

import django.db.models.deletion
import lms.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_referrals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lmssettings',
            name='affiliate_cookie_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='A purchase this many days after clicking a link still counts.'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='affiliate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Default commission for new affiliates (%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='affiliates_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Earned by the affiliate once paid (fixed when ordered).', max_digits=12),
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=lms.models.new_affiliate_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Not accepted'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('audience', models.TextField(blank=True, help_text='Where and to whom they will promote the courses.', max_length=1000)),
                ('payout_details', models.TextField(blank=True, help_text='Private: how they want to be paid.', max_length=500)),
                ('note', models.CharField(blank=True, help_text='From ADRAM: why it was not accepted or suspended.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='lms.affiliate'),
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='lms.affiliate')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateClickDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_days', to='lms.affiliate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('affiliate', 'date'), name='one_click_row_per_day')],
            },
        ),
    ]
