# Generated by Django 6.1.1 on 2026-10-02 14:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_flash_sales'),
        ('lms', '0021_campaigns'),
        ('portal', '0016_card_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='instalment_grace_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Lessons lock when a part is this many days overdue.'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='instalment_max_parts',
            field=models.PositiveSmallIntegerField(default=3, help_text='2 or 3.'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='instalment_min_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('300'), help_text='Courses from this price can be paid in parts.', max_digits=10),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='instalments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='premium_enabled',
            field=models.BooleanField(default=True, help_text='Students can subscribe to a plan that opens every Premium course.'),
        ),
        migrations.AddField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='Instalments: pay by this date.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instalment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstalmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parts', models.PositiveSmallIntegerField()),
                ('paid_parts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Paying'), ('completed', 'Paid in full'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalment_plans', to='catalog.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='instalment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='lms.instalmentplan'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='A Premium subscription order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='lms.plan'),
        ),
        migrations.CreateModel(
            name='PremiumEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='portal.trainingenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='lms.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='lms.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ends_at'],
            },
        ),
    ]
