# Generated by Django 6.1.1 on 2026-10-02 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_active_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lmssettings',
            name='app_min_version',
            field=models.CharField(blank=True, help_text='Older app versions are asked to update (e.g. 1.2.0).', max_length=20),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='offline_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Saved lessons play offline this long before the app must check in.'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='offline_devices',
            field=models.PositiveSmallIntegerField(default=3, help_text='Devices a student can keep saved lessons on.'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='Send notifications to the mobile apps too.'),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, unique=True)),
                ('kind', models.CharField(choices=[('expo', 'Expo'), ('fcm', 'Firebase')], default='expo', max_length=6)),
                ('platform', models.CharField(blank=True, help_text='android or ios', max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_licences', to='lms.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_licences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson', 'device_id'), name='one_licence_per_device_lesson')],
            },
        ),
    ]
