# Generated by Django 6.1.1 on 2026-10-02 16:41

import django.core.files.storage
import django.db.models.deletion
import lms.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_study_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='A language code: en, fr, kri…', max_length=10)),
                ('label', models.CharField(help_text='Shown in the player: English, Français, Krio…', max_length=40)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/RAHMAN/Documents/Adram Website/backend/private_media')), upload_to=lms.models.caption_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='lms.lesson')),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'language'), name='one_caption_per_language')],
            },
        ),
    ]
