# Generated by Django 6.1.1 on 2026-10-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_peer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='similar_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='similarity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='% of wording shared with another student’s work (highest).', null=True),
        ),
    ]
