# Generated by Django 6.1.1 on 2026-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_submission_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmssettings',
            name='max_streams',
            field=models.PositiveSmallIntegerField(default=2, help_text='Devices that may play videos at the same time on one account (0 = no limit).'),
        ),
        migrations.AddField(
            model_name='lmssettings',
            name='watermark_videos',
            field=models.BooleanField(default=True, help_text='Show the student’s email faintly over videos.'),
        ),
    ]
