# Generated by Django 6.1.1 on 2026-10-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, default='network', help_text='A brand icon name, e.g. network.', max_length=40)),
                ('summary', models.CharField(blank=True, help_text='One or two sentences, shown on the field card.', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Markdown: who it is for and what learners will be able to do.', max_length=6000)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Zero'), (2, 'Foundations'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Hero')], default=1)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.field')),
            ],
            options={
                'ordering': ['level', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('research', 'Research note'), ('lab', 'Hands-on lab'), ('cheatsheet', 'Cheat sheet')], default='note', max_length=12)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('body', models.TextField(blank=True, max_length=60000)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.field')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.topic')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoteProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'note'), name='learning_progress_once')],
            },
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('field', 'slug'), name='learning_note_slug_per_field'),
        ),
    ]
