# Generated by Django 6.1.1 on 2026-10-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='helpful_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='helpful_yes',
            field=models.PositiveIntegerField(default=0, help_text='Readers who found the article helpful.'),
        ),
    ]
