// Describes what the admin can edit on each page: the form in Website → Site content is built from this.
//
// A section groups fields. A field is { type, path, label, hint?, ... }, where `path` says where its value is
// kept in the page's content (e.g. 'hero.title'); it must match content/defaults.js.
//   type: 'text' | 'textarea' | 'link' | 'image' | 'icon' | 'number' | 'select' | 'weekdays' | 'theme'
//       | 'strings' (a list of short lines)
//       | 'list' (a list of cards: `fields` describe each card, `titleField` is the path shown as its heading)
// Add a page here (and to CONTENT_PAGES in backend/cms/models.py and to content/defaults.js) to make it editable.

const toggle = (path, label, extra) => ({ type: 'toggle', path, label, ...extra });
// A heading inside a list card, to break a long form into parts
const divider = (label, hint) => ({ type: 'heading', path: `_${label}`, label, hint });
const text = (path, label, extra) => ({ type: 'text', path, label, ...extra });
const area = (path, label, extra) => ({ type: 'textarea', path, label, rows: 3, ...extra });
const link = (path, label, extra) => ({ type: 'link', path, label, hint: 'A page on this site, like /services, or a full web address.', ...extra });
const image = (path, label, extra) => ({ type: 'image', path, label, ...extra });
const icon = (path = 'icon', label = 'Icon') => ({ type: 'icon', path, label });
const strings = (path, label, extra) => ({ type: 'strings', path, label, ...extra });

// Wording shared by many sections: {location}, {name}, {tagline} are filled in from the site-wide details
const TOKENS = 'You can use {location} and {name}: they are replaced with the company details.';

const cta = (path = 'cta') => ({
  id: 'cta',
  title: 'Contact banner',
  description: 'The blue call-to-action band at the bottom of the page.',
  fields: [text(`${path}.title`, 'Heading'), area(`${path}.text`, 'Text')],
});

export const NETWORK_OPTIONS = [
  ['facebook', 'Facebook'],
  ['whatsapp', 'WhatsApp'],
  ['instagram', 'Instagram'],
  ['x', 'X (Twitter)'],
  ['linkedin', 'LinkedIn'],
  ['youtube', 'YouTube'],
  ['tiktok', 'TikTok'],
  ['telegram', 'Telegram'],
  ['github', 'GitHub'],
];

// Turns a title into a page address: "IT Consultancy" -> "it-consultancy"
export const slugify = (value) =>
  String(value || '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);

/** New services get their page address from the title, kept unique; existing addresses are left alone. */
const normalizeServices = (form) => {
  const taken = new Set();
  const items = (form.items || []).map((item) => {
    let id = slugify(item.id) || slugify(item.title) || 'service';
    const base = id;
    for (let n = 2; taken.has(id); n += 1) id = `${base}-${n}`;
    taken.add(id);
    return id === item.id ? item : { ...item, id };
  });
  return { ...form, items };
};

export const contentPages = [
  // ------------------------------------------------------------------ Site-wide
  {
    slug: 'site',
    label: 'Contact details & footer',
    icon: 'fa-address-card',
    description: 'Company name, colours, phone numbers, email, address, opening hours and social links. Shown in the header, footer, contact page and buttons across the whole website.',
    publicPath: '/contact',
    sections: [
      {
        id: 'company',
        title: 'Company',
        fields: [
          text('name', 'Company name'),
          text('shortName', 'Short name'),
          text('tagline', 'Tagline'),
          text('brandName', 'Logo text: name', { hint: 'The large word next to the logo mark, e.g. ADRAM.' }),
          text('brandSub', 'Logo text: line under the name', { hint: 'e.g. Technologies.' }),
          image('logo', 'Logo mark', { hint: 'A square image, shown in the header, footer and sign-in screens.' }),
          image('heroLogo', 'Logo on the home banner', { hint: 'The larger logo shown in the round badge on the home page banner and About page.' }),
          area('footerBlurb', 'Footer description', { hint: `The short paragraph under the logo in the footer. ${TOKENS}` }),
        ],
      },
      {
        id: 'colours',
        title: 'Colours',
        description: 'The colour scheme of the whole website and portal: buttons, links, banners, the footer and the drawings. Pick a ready-made scheme or your own three colours. Each portal user can still choose their own accent colour for their dashboard.',
        fields: [{ type: 'theme', path: 'theme', label: 'Colour scheme' }],
      },
      {
        id: 'icons',
        title: 'Tab icon & link previews',
        description: 'The small icon on the browser tab, and what WhatsApp, Facebook and LinkedIn show when someone shares a link to the website. Leave the preview fields empty to keep the original text and picture. A page’s own “Search & browser title” is used for its link preview when you have edited it.',
        fields: [
          image('favicon', 'Browser tab icon (favicon)', { hint: 'A small square image, ideally 192 × 192 pixels or larger.' }),
          text('share.title', 'Link preview: title', { hint: 'Shown as the headline of a shared link.' }),
          area('share.description', 'Link preview: description', { hint: 'One or two sentences, about 150 characters.' }),
          image('share.image', 'Link preview: picture', { hint: 'A wide picture, 1200 × 630 pixels works best. Link previews are written by the Django server, so they need the website to be served by Django.' }),
        ],
      },
      {
        id: 'contact',
        title: 'Contact details',
        fields: [
          text('email', 'Email address', { inputType: 'email' }),
          strings('phones', 'Phone numbers', { itemLabel: 'Phone number', placeholder: '+232 76 000 000', max: 5, hint: 'The first number is the one shown in the header and on “Call” buttons.' }),
          text('location', 'Location', { hint: 'City and country, e.g. Freetown, Sierra Leone.' }),
        ],
      },
      {
        id: 'hours',
        title: 'Opening hours',
        description: 'Used on the contact page and to show whether the office is open right now.',
        fields: [
          {
            type: 'list',
            path: 'hours',
            label: 'Opening times',
            itemName: 'time slot',
            titleField: 'days',
            max: 7,
            blank: { days: '', short: '', time: '', weekdays: [], open: '', close: '' },
            fields: [
              text('days', 'Days', { placeholder: 'Monday – Friday' }),
              text('short', 'Short form', { placeholder: 'Mon – Fri', hint: 'Used in the header and footer.' }),
              text('time', 'Hours as shown', { placeholder: '9:00 AM – 6:00 PM', hint: 'Write Closed for days off.' }),
              { type: 'weekdays', path: 'weekdays', label: 'Which days' },
              { type: 'number', path: 'open', label: 'Opens at (hour, 0–23)', min: 0, max: 23, hint: 'Leave blank when closed.' },
              { type: 'number', path: 'close', label: 'Closes at (hour, 1–24)', min: 1, max: 24, hint: 'Leave blank when closed.' },
            ],
          },
        ],
      },
      {
        id: 'socials',
        title: 'Social media',
        description: 'Icons shown in the header, footer, contact page and sign-in pages. Only networks with a link are shown.',
        fields: [
          {
            type: 'list',
            path: 'socials',
            label: 'Social links',
            itemName: 'link',
            titleField: 'id',
            max: 9,
            blank: { id: 'facebook', href: '' },
            fields: [
              { type: 'select', path: 'id', label: 'Network', options: NETWORK_OPTIONS },
              link('href', 'Link', { hint: 'The full web address of your profile or page. For WhatsApp: https://wa.me/ followed by the number with the country code.' }),
            ],
          },
        ],
      },
    ],
  },

  // ------------------------------------------------------------------ Home
  {
    slug: 'home',
    label: 'Home page',
    icon: 'fa-house',
    description: 'The main banner, highlights, service section, about block, process, sectors and the training and scholarship cards.',
    publicPath: '/',
    sections: [
      {
        id: 'hero',
        title: 'Main banner',
        fields: [
          text('hero.badge', 'Small badge above the heading', { hint: TOKENS }),
          text('hero.titleStart', 'Heading, first part'),
          text('hero.titleAccent', 'Heading, highlighted part', { hint: 'Shown in the brand colour.' }),
          area('hero.lead', 'Introduction', { hint: TOKENS }),
          text('hero.primaryLabel', 'Main button text'),
          link('hero.primaryLink', 'Main button link'),
          text('hero.secondaryLabel', 'Second button text'),
          link('hero.secondaryLink', 'Second button link'),
          strings('hero.trust', 'Points under the buttons', { itemLabel: 'Point', max: 5, placeholder: 'e.g. Local support team' }),
          strings('hero.badges', 'Labels on the four logo-panel badges', { itemLabel: 'Label', max: 4, placeholder: 'e.g. Software', hint: 'Shown when someone hovers a badge on the logo panel: in order, top left, top right, bottom right, bottom left.' }),
        ],
      },
      {
        id: 'highlights',
        title: 'Highlights strip',
        description: 'The four quick links under the main banner.',
        fields: [
          {
            type: 'list',
            path: 'highlights',
            label: 'Highlights',
            itemName: 'highlight',
            titleField: 'title',
            max: 4,
            blank: { icon: 'software', title: '', text: '', link: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Short text'), link('link', 'Link')],
          },
        ],
      },
      {
        id: 'services',
        title: 'Services section',
        description: 'The heading and buttons. Which services appear here is set with each service (coming in the next update).',
        fields: [
          text('services.eyebrow', 'Small label'),
          text('services.title', 'Heading'),
          area('services.intro', 'Introduction'),
          text('services.headerButton', 'Button beside the heading'),
          text('services.cardButton', 'Text on each service card', { hint: 'e.g. Learn more' }),
          text('services.helpTitle', '“Not sure” card: heading'),
          area('services.helpText', '“Not sure” card: text'),
          text('services.helpButton', '“Not sure” card: button'),
          link('services.helpLink', '“Not sure” card: link'),
          text('services.allButton', 'Big button under the cards', { hint: 'Use {count} for the number of services.' }),
        ],
      },
      {
        id: 'about',
        title: 'About block',
        fields: [
          text('about.eyebrow', 'Small label'),
          text('about.title', 'Heading'),
          area('about.text', 'Introduction', { hint: TOKENS }),
          {
            type: 'list',
            path: 'about.reasons',
            label: 'Reasons to choose us',
            itemName: 'reason',
            titleField: 'title',
            max: 6,
            blank: { icon: 'shield', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text', { hint: TOKENS })],
          },
          text('about.serviceCountLabel', 'Number label: services'),
          text('about.trainingCountLabel', 'Number label: training tracks'),
          text('about.replyLabel', 'Number label: reply time'),
          text('about.replyValue', 'Typical reply time', { placeholder: '1 day' }),
          text('about.button', 'Button text'),
          link('about.buttonLink', 'Button link'),
        ],
      },
      {
        id: 'process',
        title: 'How we work',
        fields: [
          text('process.eyebrow', 'Small label'),
          text('process.title', 'Heading'),
          area('process.intro', 'Introduction'),
          {
            type: 'list',
            path: 'process.steps',
            label: 'Steps',
            itemName: 'step',
            titleField: 'title',
            max: 6,
            blank: { icon: 'discover', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      {
        id: 'sectors',
        title: 'Sectors we serve',
        fields: [
          text('sectors.eyebrow', 'Small label'),
          text('sectors.title', 'Heading'),
          area('sectors.intro', 'Introduction'),
          {
            type: 'list',
            path: 'sectors.items',
            label: 'Sectors',
            itemName: 'sector',
            titleField: 'title',
            max: 12,
            blank: { icon: 'growth', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      {
        id: 'talent',
        title: 'Training & scholarships cards',
        fields: [
          text('talent.eyebrow', 'Small label'),
          text('talent.title', 'Heading'),
          area('talent.intro', 'Introduction'),
          image('talent.training.image', 'Training card: photo'),
          text('talent.training.tag', 'Training card: photo tag', { hint: 'Use {count} for the number of training programmes.' }),
          text('talent.training.eyebrow', 'Training card: small label'),
          text('talent.training.title', 'Training card: heading'),
          area('talent.training.text', 'Training card: text'),
          text('talent.training.button', 'Training card: button'),
          link('talent.training.link', 'Training card: link'),
          image('talent.scholarships.image', 'Scholarships card: photo'),
          text('talent.scholarships.tag', 'Scholarships card: photo tag'),
          text('talent.scholarships.eyebrow', 'Scholarships card: small label'),
          text('talent.scholarships.title', 'Scholarships card: heading'),
          area('talent.scholarships.text', 'Scholarships card: text'),
          text('talent.scholarships.button', 'Scholarships card: main button'),
          link('talent.scholarships.link', 'Scholarships card: main link'),
          text('talent.scholarships.secondaryButton', 'Scholarships card: second button'),
          link('talent.scholarships.secondaryLink', 'Scholarships card: second link'),
        ],
      },
      cta(),
    ],
  },

  // ------------------------------------------------------------------ About
  {
    slug: 'about',
    label: 'About page',
    icon: 'fa-building',
    description: 'The About header, who we are, the three pillars, mission and vision, and values.',
    publicPath: '/about',
    sections: [
      {
        id: 'hero',
        title: 'Page header',
        fields: [
          text('hero.eyebrow', 'Small label'),
          text('hero.title', 'Heading', { hint: TOKENS }),
          area('hero.lead', 'Introduction', { hint: TOKENS }),
          image('hero.image', 'Background photo'),
        ],
      },
      {
        id: 'who',
        title: 'Who we are',
        fields: [
          text('who.eyebrow', 'Small label'),
          text('who.title', 'Heading'),
          area('who.lead', 'First paragraph'),
          area('who.text', 'Second paragraph'),
        ],
      },
      {
        id: 'pillars',
        title: 'Pillars',
        description: 'The cards under “Who we are”.',
        fields: [
          {
            type: 'list',
            path: 'pillars',
            label: 'Pillars',
            itemName: 'pillar',
            titleField: 'title',
            max: 6,
            blank: { icon: 'server', title: '', text: '', link: '' },
            fields: [icon(), text('title', 'Title'), area('text', 'Text'), link('link', 'Link')],
          },
        ],
      },
      {
        id: 'mission',
        title: 'Mission',
        fields: [icon('mission.icon'), text('mission.eyebrow', 'Small label'), text('mission.title', 'Statement'), area('mission.text', 'Text')],
      },
      {
        id: 'vision',
        title: 'Vision',
        fields: [icon('vision.icon'), text('vision.eyebrow', 'Small label'), text('vision.title', 'Statement'), area('vision.text', 'Text')],
      },
      {
        id: 'values',
        title: 'Values',
        fields: [
          text('values.eyebrow', 'Small label'),
          text('values.title', 'Heading'),
          {
            type: 'list',
            path: 'values.items',
            label: 'Values',
            itemName: 'value',
            titleField: 'title',
            max: 8,
            blank: { icon: 'quality', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      cta(),
    ],
  },

  // ------------------------------------------------------------------ Services
  {
    slug: 'services',
    label: 'Services',
    icon: 'fa-laptop-code',
    description: 'The Services page, every service card and each service’s own page. Add or remove services, put them in order, and choose which ones appear on the home page. The order here is also the order in the menu and footer.',
    publicPath: '/services',
    normalize: normalizeServices,
    sections: [
      {
        id: 'hero',
        title: 'Services page header',
        fields: [
          text('hero.eyebrow', 'Small label'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction', { hint: 'Use {count} for the number of services.' }),
          image('hero.image', 'Background photo'),
          text('hero.primaryLabel', 'Main button text'),
          text('hero.secondaryLabel', 'Second button text'),
        ],
      },
      {
        id: 'items',
        title: 'Services',
        description: 'Each service has a card (on the Services page, the home page, the menu and the footer) and its own page. New services get a page address from their title.',
        fields: [
          {
            type: 'list',
            path: 'items',
            label: 'All services',
            itemName: 'service',
            titleField: 'title',
            max: 30,
            blank: {
              id: '',
              title: '',
              icon: 'server',
              summary: '',
              includes: [],
              image: '',
              heroImage: '',
              featured: false,
              details: { tagline: '', overview: [], idealFor: [], benefits: [], process: [], overviewImage: '', asideImage: '', featuredTech: [], techStack: [], faqs: [] },
            },
            fields: [
              divider('Card'),
              text('title', 'Service name'),
              text('id', 'Page address', { hint: 'Used in the link, e.g. /services/web-development. Leave blank for a new service. Changing it breaks old links to this page.' }),
              icon('icon', 'Icon'),
              area('summary', 'Short description', { hint: 'One or two sentences: shown on the cards.' }),
              strings('includes', 'What’s included', { itemLabel: 'Item', max: 8, placeholder: 'e.g. Company websites and portals' }),
              image('image', 'Card photo', { hint: 'Shown on the service cards.' }),
              toggle('featured', 'Show on the home page', { hint: 'Featured services are listed on the home page.' }),
              divider('Service page'),
              image('heroImage', 'Page header photo'),
              text('details.tagline', 'Tagline', { hint: 'The sentence under the page heading.' }),
              strings('details.overview', 'Overview paragraphs', { itemLabel: 'Paragraph', max: 6, placeholder: 'A paragraph about the service' }),
              image('details.overviewImage', 'Overview photo'),
              image('details.asideImage', 'Contact card photo', { hint: 'Behind the “Interested in…” card on the side.' }),
              strings('details.idealFor', 'Who it’s for', { itemLabel: 'Audience', max: 8, placeholder: 'e.g. Schools and training centres' }),
              {
                type: 'list',
                path: 'details.benefits',
                label: 'Why it matters',
                itemName: 'benefit',
                titleField: 'title',
                max: 8,
                blank: { icon: 'shield', title: '', text: '' },
                fields: [icon(), text('title', 'Title'), text('text', 'Text')],
              },
              {
                type: 'list',
                path: 'details.process',
                label: 'How we deliver it',
                itemName: 'step',
                titleField: 'title',
                max: 8,
                blank: { title: '', text: '' },
                fields: [text('title', 'Step title'), text('text', 'Text')],
              },
              {
                type: 'list',
                path: 'details.techStack',
                label: 'Tools & technologies',
                itemName: 'group',
                titleField: 'group',
                max: 8,
                blank: { group: '', icon: 'fa-screwdriver-wrench', items: [] },
                fields: [
                  text('group', 'Group name', { placeholder: 'e.g. Frontend' }),
                  text('icon', 'Group icon', { placeholder: 'fa-database', hint: 'A Font Awesome icon name, such as fa-database, fa-server or fa-code.' }),
                  {
                    type: 'list',
                    path: 'items',
                    label: 'Tools',
                    itemName: 'tool',
                    titleField: 'name',
                    max: 30,
                    blank: { name: '', logo: 'git' },
                    fields: [text('name', 'Name'), { type: 'logo', path: 'logo', label: 'Logo' }],
                  },
                ],
              },
              strings('details.featuredTech', 'Logos on the overview photo', { itemLabel: 'Logo', max: 5, placeholder: 'e.g. react', hint: 'Up to 4 logo names taken from the tools above (the name shown in the Logo list).' }),
              {
                type: 'list',
                path: 'details.faqs',
                label: 'Frequently asked questions',
                itemName: 'question',
                titleField: 'q',
                max: 12,
                blank: { q: '', a: '' },
                fields: [text('q', 'Question'), area('a', 'Answer')],
              },
            ],
          },
        ],
      },
      {
        id: 'labels',
        title: 'Service page headings and buttons',
        description: 'The wording around every service’s content. Use {service} for the service name.',
        fields: [
          text('labels.included', 'Card list heading'),
          text('labels.viewDetails', 'Card button: view details'),
          text('labels.contact', 'Card button: contact'),
          text('labels.overviewEyebrow', 'Overview: small label'),
          text('labels.overview', 'Overview: heading'),
          text('labels.idealFor', 'Heading: who it’s for'),
          text('labels.benefits', 'Heading: why it matters'),
          text('labels.process', 'Heading: how we deliver it'),
          text('labels.tools', 'Heading: tools & technologies'),
          text('labels.faqs', 'Heading: questions'),
          text('labels.badgeTitle', 'Photo badge: title'),
          text('labels.badgeText', 'Photo badge: text'),
          text('labels.otherServices', 'Side list heading'),
          text('labels.contactButton', 'Header button: contact'),
          text('labels.callButton', 'Header button: call'),
          text('labels.asideTitle', 'Side card: heading'),
          area('labels.asideText', 'Side card: text'),
          text('labels.bannerTitle', 'Bottom banner: heading'),
          area('labels.bannerText', 'Bottom banner: text'),
        ],
      },
      cta(),
    ],
  },

  // ------------------------------------------------------------------ Team
  {
    slug: 'team',
    label: 'Team page',
    icon: 'fa-people-group',
    description: 'The Team page header and closing panel. The members themselves are managed in Admin → Team.',
    publicPath: '/about/team',
    sections: [
      {
        id: 'hero',
        title: 'Page header',
        fields: [
          text('hero.eyebrow', 'Small label'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          image('hero.image', 'Background photo'),
          text('hero.primaryLabel', 'Main button text'),
          text('hero.secondaryLabel', 'Second button text'),
        ],
      },
      {
        id: 'members',
        title: 'Heading above the team',
        description: 'The heading over the member cards. The members themselves (and their portfolio pages) are managed in Admin → Team; the figures beside the heading come from their profiles.',
        fields: [
          text('intro.eyebrow', 'Small label'),
          text('intro.title', 'Heading'),
          area('intro.text', 'Introduction'),
        ],
      },
      cta(),
    ],
  },

  // ------------------------------------------------------------------ Training
  {
    slug: 'courses',
    label: 'Training page',
    icon: 'fa-graduation-cap',
    description: 'The Training page wording. The programmes themselves (title, summary, fee, dates) are edited under Website → Training; here you set the page around them and each programme’s photo and filter group.',
    publicPath: '/courses',
    sections: [
      {
        id: 'hero',
        title: 'Page header',
        fields: [
          text('hero.eyebrow', 'Small label'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          image('hero.image', 'Background photo'),
          text('hero.primaryLabel', 'Main button text'),
          text('hero.secondaryLabel', 'Second button text'),
        ],
      },
      {
        id: 'stats',
        title: 'At-a-glance strip',
        description: 'The row of four figures under the header. Use {count} for the number of programmes.',
        fields: [
          {
            type: 'list',
            path: 'stats',
            label: 'Figures',
            itemName: 'figure',
            titleField: 'label',
            max: 6,
            blank: { value: '', label: '' },
            fields: [text('value', 'Figure'), text('label', 'Label')],
          },
        ],
      },
      {
        id: 'programmes',
        title: 'Programmes section',
        fields: [
          text('programmes.eyebrow', 'Small label'),
          text('programmes.title', 'Heading'),
          area('programmes.intro', 'Introduction'),
          text('programmes.allLabel', 'Filter button: all programmes'),
          text('programmes.enrollLabel', 'Enroll button'),
          text('programmes.askDatesLabel', 'Link when dates and fees are not set'),
          text('programmes.askQuestionLabel', 'Link when dates and fees are set'),
          text('programmes.serviceLabel', 'Link to the matching service'),
        ],
      },
      {
        id: 'groups',
        title: 'Filter groups',
        description: 'The filter buttons above the programmes. The group ID is what each programme’s photo entry below refers to.',
        fields: [
          {
            type: 'list',
            path: 'groups',
            label: 'Groups',
            itemName: 'group',
            titleField: 'label',
            max: 12,
            blank: { id: '', label: '' },
            fields: [text('label', 'Button text'), text('id', 'Group ID', { hint: 'Letters, numbers and dashes only, e.g. data.' })],
          },
        ],
      },
      {
        id: 'meta',
        title: 'Programme photos and groups',
        description: 'A photo, filter group and matching service for each programme. The programme ID is its page anchor from Website → Training (for example touch-typing).',
        fields: [
          {
            type: 'list',
            path: 'meta',
            label: 'Programmes',
            itemName: 'programme',
            titleField: 'slug',
            max: 60,
            blank: { slug: '', image: '', group: '', service: '' },
            fields: [
              text('slug', 'Programme ID', { hint: 'The page anchor shown in the programme’s publishing box.' }),
              image('image', 'Card photo'),
              text('group', 'Filter group ID', { hint: 'One of the group IDs above.' }),
              text('service', 'Matching service address', { hint: 'For example web-development. Leave blank for none.' }),
            ],
          },
        ],
      },
      {
        id: 'reasons',
        title: 'Why train with us',
        fields: [
          text('reasons.eyebrow', 'Small label'),
          text('reasons.title', 'Heading'),
          {
            type: 'list',
            path: 'reasons.items',
            label: 'Reasons',
            itemName: 'reason',
            titleField: 'title',
            max: 8,
            blank: { icon: 'laptop', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      {
        id: 'how',
        title: 'How it works',
        fields: [
          text('how.eyebrow', 'Small label'),
          text('how.title', 'Heading'),
          area('how.intro', 'Introduction'),
          {
            type: 'list',
            path: 'how.steps',
            label: 'Steps',
            itemName: 'step',
            titleField: 'title',
            max: 8,
            blank: { title: '', text: '' },
            fields: [text('title', 'Title'), area('text', 'Text')],
          },
        ],
      },
      {
        id: 'formats',
        title: 'Ways to learn',
        fields: [
          text('formats.eyebrow', 'Small label'),
          text('formats.title', 'Heading'),
          {
            type: 'list',
            path: 'formats.items',
            label: 'Formats',
            itemName: 'format',
            titleField: 'title',
            max: 6,
            blank: { icon: 'classroom', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      {
        id: 'faqs',
        title: 'Questions and answers',
        fields: [
          text('faqs.eyebrow', 'Small label'),
          text('faqs.title', 'Heading'),
          {
            type: 'list',
            path: 'faqs.items',
            label: 'Questions',
            itemName: 'question',
            titleField: 'q',
            max: 15,
            blank: { q: '', a: '' },
            fields: [text('q', 'Question'), area('a', 'Answer')],
          },
        ],
      },
      cta(),
    ],
  },

  // ------------------------------------------------------------------ Scholarships
  {
    slug: 'scholarships',
    label: 'Scholarships page',
    icon: 'fa-award',
    description: 'The Scholarships page and each scholarship page’s headings and buttons. The scholarships themselves are edited under Website → Scholarships.',
    publicPath: '/scholarships',
    sections: [
      {
        id: 'hero',
        title: 'Page header',
        fields: [
          text('hero.eyebrow', 'Small label'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          image('hero.image', 'Background photo'),
          text('hero.primaryLabel', 'Main button text'),
          text('hero.secondaryLabel', 'Second button text'),
        ],
      },
      {
        id: 'stats',
        title: 'Figures strip',
        description: 'Labels for the four figures under the header. The numbers are counted from your scholarship list.',
        fields: [
          text('stats.listed', 'Label: scholarships listed'),
          text('stats.destinations', 'Label: study destinations'),
          text('stats.funded', 'Label: fully funded'),
          text('stats.levels', 'Label: levels of study'),
        ],
      },
      {
        id: 'finder',
        title: 'Scholarship finder',
        fields: [
          text('finder.eyebrow', 'Small label'),
          text('finder.title', 'Heading'),
          area('finder.intro', 'Introduction'),
          area('finder.disclaimer', 'Notice under the list'),
        ],
      },
      {
        id: 'destinations',
        title: 'Study destinations',
        fields: [text('destinations.eyebrow', 'Small label'), text('destinations.title', 'Heading'), area('destinations.intro', 'Introduction')],
      },
      {
        id: 'help',
        title: 'How we help',
        fields: [
          text('help.eyebrow', 'Small label'),
          text('help.title', 'Heading'),
          area('help.intro', 'Introduction'),
          image('help.image', 'Photo'),
          text('help.caption', 'Photo caption'),
          {
            type: 'list',
            path: 'help.items',
            label: 'Ways we help',
            itemName: 'item',
            titleField: 'title',
            max: 8,
            blank: { icon: 'support', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      {
        id: 'journey',
        title: 'Application journey',
        fields: [
          text('journey.title', 'Heading'),
          {
            type: 'list',
            path: 'journey.steps',
            label: 'Steps',
            itemName: 'step',
            titleField: 'title',
            max: 8,
            blank: { title: '', text: '' },
            fields: [text('title', 'Title'), area('text', 'Text')],
          },
          text('journey.createLabel', 'Button: create account'),
          text('journey.signInLabel', 'Button: sign in'),
        ],
      },
      {
        id: 'docs',
        title: 'Documents to prepare',
        description: 'Shown on this page and on every scholarship page.',
        fields: [
          text('docs.title', 'Heading'),
          area('docs.intro', 'Introduction'),
          image('docs.image', 'Photo'),
          strings('docs.items', 'Documents', { itemLabel: 'Document', max: 15, placeholder: 'e.g. Valid international passport' }),
        ],
      },
      {
        id: 'faqs',
        title: 'Questions and answers',
        fields: [
          text('faqs.eyebrow', 'Small label'),
          text('faqs.title', 'Heading'),
          {
            type: 'list',
            path: 'faqs.items',
            label: 'Questions',
            itemName: 'question',
            titleField: 'q',
            max: 15,
            blank: { q: '', a: '' },
            fields: [text('q', 'Question'), area('a', 'Answer')],
          },
        ],
      },
      {
        id: 'detail',
        title: 'Scholarship page headings and buttons',
        description: 'The wording around each scholarship’s own page. Use {name} for the scholarship’s name.',
        fields: [
          text('detail.overviewEyebrow', 'Overview: small label'),
          text('detail.overviewTitle', 'Overview: heading'),
          text('detail.keyDates', 'Heading: key dates'),
          area('detail.datesNote', 'Note under key dates'),
          text('detail.covers', 'Heading: what it covers'),
          text('detail.eligibility', 'Heading: who can apply'),
          text('detail.steps', 'Heading: how to apply'),
          text('detail.documents', 'Heading: documents'),
          text('detail.helpTitle', 'Support banner: heading'),
          area('detail.helpText', 'Support banner: text'),
          text('detail.helpButton', 'Support banner: button'),
          text('detail.keyFacts', 'Side box: key facts heading'),
          text('detail.moreTitle', 'Side box: more scholarships heading'),
          text('detail.moreLink', 'Side box: browse link'),
          text('detail.trackTitle', 'Side card: heading'),
          area('detail.trackText', 'Side card: text'),
          text('detail.trackButton', 'Side card: main button'),
          text('detail.questionButton', 'Side card: second button'),
          text('detail.bannerTitle', 'Bottom banner: heading'),
          area('detail.bannerText', 'Bottom banner: text'),
        ],
      },
      cta(),
    ],
  },

  // ------------------------------------------------------------------ Contact
  {
    slug: 'contact',
    label: 'Contact page',
    icon: 'fa-envelope-open-text',
    description: 'The Contact page wording: header, the four contact cards, the enquiry form, office-hours box and map button. Phone, email, address, hours and social links are under Contact details & footer.',
    publicPath: '/contact',
    sections: [
      {
        id: 'hero',
        title: 'Page header',
        fields: [
          text('hero.eyebrow', 'Small label'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          text('hero.callLabel', 'Call button', { hint: 'Use {phone} for the first phone number.' }),
          text('hero.whatsappLabel', 'WhatsApp button'),
        ],
      },
      {
        id: 'methods',
        title: 'Contact cards',
        fields: [
          text('methods.callTitle', 'Call: title'),
          text('methods.callAction', 'Call: link text'),
          text('methods.whatsappTitle', 'WhatsApp: title'),
          text('methods.whatsappValue', 'WhatsApp: line under the title'),
          text('methods.whatsappAction', 'WhatsApp: link text'),
          text('methods.emailTitle', 'Email: title'),
          text('methods.emailAction', 'Email: link text'),
          text('methods.visitTitle', 'Visit: title'),
          text('methods.visitAction', 'Visit: link text'),
        ],
      },
      {
        id: 'form',
        title: 'Enquiry form',
        fields: [
          text('form.title', 'Heading'),
          area('form.intro', 'Introduction'),
          text('form.badge', 'Reply-time badge'),
          text('form.topicsLabel', 'Topic buttons label'),
          strings('topics', 'Topic buttons', { itemLabel: 'Topic', max: 12, placeholder: 'e.g. Web development', hint: 'Choosing one fills in the subject as “Topic enquiry”.' }),
          text('form.nameLabel', 'Name label'),
          text('form.namePlaceholder', 'Name hint text'),
          text('form.emailLabel', 'Email label'),
          text('form.emailPlaceholder', 'Email hint text'),
          text('form.subjectLabel', 'Subject label'),
          text('form.subjectPlaceholder', 'Subject hint text'),
          text('form.messageLabel', 'Message label'),
          text('form.messagePlaceholder', 'Message hint text'),
          text('form.privacyNote', 'Privacy note'),
          text('form.sendLabel', 'Send button'),
        ],
      },
      {
        id: 'sent',
        title: 'After sending',
        fields: [
          text('form.sentTitle', 'Heading'),
          area('form.sentText', 'Text'),
          text('form.sentAgainLabel', 'Button: send another'),
          text('form.sentWhatsappLabel', 'Button: WhatsApp'),
        ],
      },
      {
        id: 'aside',
        title: 'Side boxes and map',
        fields: [
          text('hours.title', 'Office hours: heading'),
          text('hours.openLabel', 'Office hours: open label'),
          text('hours.closedLabel', 'Office hours: closed label'),
          text('hours.todayLabel', 'Office hours: “today” tag'),
          text('hours.note', 'Office hours: note'),
          text('follow.title', 'Follow us: heading'),
          area('follow.text', 'Follow us: text'),
          text('students.title', 'Students: heading'),
          area('students.text', 'Students: text'),
          text('students.link', 'Students: link text'),
          text('map.button', 'Map card button'),
        ],
      },
    ],
  },

  // ------------------------------------------------------------------ Navigation
  {
    slug: 'navigation',
    label: 'Menus & footer links',
    icon: 'fa-bars',
    description: 'The header menu labels and dropdown links, and the footer’s column titles, links and small print.',
    publicPath: '/',
    sections: [
      {
        id: 'labels',
        title: 'Header menu',
        fields: [
          text('labels.home', 'Home'),
          text('labels.about', 'About'),
          text('labels.services', 'Services'),
          text('labels.training', 'Training'),
          text('labels.learningInServices', 'Learning hub link in the Services menu'),
          text('labels.scholarships', 'Scholarships'),
          text('labels.contact', 'Contact'),
          text('labels.signIn', 'Sign in button'),
          text('labels.signUp', 'Sign up button'),
          text('labels.dashboard', 'Dashboard button (signed-in visitors)'),
        ],
      },
      {
        id: 'limits',
        title: 'How many items to list',
        description: 'The Services and Training dropdowns and the footer show only the first few, then link to the full page.',
        fields: [
          { type: 'number', path: 'limits.dropdown', label: 'Items in the Services and Training dropdowns', min: 3, max: 12 },
          { type: 'number', path: 'limits.footerServices', label: 'Services in the footer', min: 3, max: 12 },
        ],
      },
      {
        id: 'about',
        title: 'About dropdown',
        fields: [
          {
            type: 'list',
            path: 'aboutMenu',
            label: 'Links',
            itemName: 'link',
            titleField: 'label',
            max: 10,
            blank: { label: '', link: '', icon: 'building' },
            fields: [text('label', 'Text'), link('link', 'Link'), icon()],
          },
        ],
      },
      {
        id: 'scholarships',
        title: 'Scholarships dropdown',
        fields: [
          {
            type: 'list',
            path: 'scholarshipsMenu',
            label: 'Links',
            itemName: 'link',
            titleField: 'label',
            max: 10,
            blank: { label: '', link: '', icon: 'award' },
            fields: [text('label', 'Text'), link('link', 'Link'), icon()],
          },
        ],
      },
      {
        id: 'menuFooters',
        title: 'Dropdown “see all” links',
        description: 'The last line of each dropdown. Use {count} for the number of items.',
        fields: [
          text('menuFooters.services', 'Services (few items)'),
          text('menuFooters.servicesMany', 'Services (more than shown)'),
          text('menuFooters.training', 'Training (few items)'),
          text('menuFooters.trainingMany', 'Training (more than shown)'),
          text('menuFooters.scholarships', 'Scholarships'),
        ],
      },
      {
        id: 'footer',
        title: 'Footer',
        fields: [
          text('footer.servicesTitle', 'Services column: title'),
          text('footer.servicesMore', 'Services column: “view all” link'),
          text('footer.companyTitle', 'Company column: title'),
          {
            type: 'list',
            path: 'footer.company',
            label: 'Company links',
            itemName: 'link',
            titleField: 'label',
            max: 10,
            blank: { label: '', link: '' },
            fields: [text('label', 'Text'), link('link', 'Link')],
          },
          text('footer.studentsTitle', 'Students column: title'),
          {
            type: 'list',
            path: 'footer.students',
            label: 'Students links',
            itemName: 'link',
            titleField: 'label',
            max: 10,
            blank: { label: '', link: '' },
            fields: [text('label', 'Text'), link('link', 'Link')],
          },
          text('footer.contactTitle', 'Contact column: title'),
          text('footer.rights', 'Copyright line ending', { hint: 'Shown after “© year Company name.”' }),
          {
            type: 'list',
            path: 'footer.bottomLinks',
            label: 'Links in the bottom bar',
            itemName: 'link',
            titleField: 'label',
            max: 6,
            blank: { label: '', link: '' },
            fields: [text('label', 'Text'), link('link', 'Link')],
          },
          text('footer.backToTop', '“Back to top” button'),
        ],
      },
    ],
  },

  // ------------------------------------------------------------------ Premium, bundles, certificate check
  {
    slug: 'store',
    label: 'Premium, bundles & certificates',
    icon: 'fa-crown',
    description: 'The wording on the Premium page, the Course bundles page and the Verify a certificate page. Plans, prices and bundles are set under Learning in the admin menu.',
    publicPath: '/premium',
    sections: [
      {
        id: 'premium',
        title: 'Premium page',
        fields: [
          text('premium.title', 'Heading'),
          area('premium.lead', 'Introduction', { hint: '{count} is replaced with the number of Premium courses.' }),
          strings('premium.benefits', 'What every plan includes', { max: 8 }),
          text('premium.button', 'Button'),
          text('premium.buttonRenew', 'Button for people who already have Premium'),
          text('premium.unavailable', 'Message when Premium is switched off'),
          text('premium.more', 'Line under the plans'),
        ],
      },
      {
        id: 'bundles',
        title: 'Course bundles page',
        fields: [text('bundles.title', 'Heading'), area('bundles.lead', 'Introduction'), text('bundles.empty', 'Message when there are no bundles')],
      },
      {
        id: 'verify',
        title: 'Verify a certificate page',
        fields: [text('verify.eyebrow', 'Small label above the heading'), text('verify.title', 'Heading'), area('verify.lead', 'Introduction')],
      },
    ],
  },

  // ------------------------------------------------------------------ Partners
  {
    slug: 'partners',
    label: 'Partners page',
    icon: 'fa-handshake',
    description: 'The wording, numbers, benefits and application form on the Partners page. The partners and their logos are added under Partners in the admin menu.',
    publicPath: '/partners',
    sections: [
      {
        id: 'hero',
        title: 'Page heading',
        fields: [
          text('hero.eyebrow', 'Small label above the heading'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          text('hero.primaryLabel', 'Main button'),
          text('hero.secondaryLabel', 'Second button'),
          {
            type: 'list', path: 'stats', label: 'Key numbers', itemName: 'number', titleField: 'label', max: 4,
            blank: { value: '', label: '' }, fields: [text('value', 'Number', { placeholder: '25+' }), text('label', 'Label')],
          },
        ],
      },
      {
        id: 'logos',
        title: 'Partner logos & quotes',
        fields: [text('logosTitle', 'Logos heading'), area('logosLead', 'Logos introduction'), text('spotlightTitle', 'Quotes heading')],
      },
      {
        id: 'benefits',
        title: 'Why partner with us',
        fields: [
          text('benefitsTitle', 'Heading'),
          area('benefitsLead', 'Introduction'),
          {
            type: 'list', path: 'benefits', label: 'Benefits', itemName: 'benefit', titleField: 'title', max: 6,
            blank: { icon: 'partnership', title: '', text: '' }, fields: [icon(), text('title', 'Title'), area('text', 'Text')],
          },
        ],
      },
      {
        id: 'steps',
        title: 'How it works',
        fields: [
          text('stepsTitle', 'Heading'),
          {
            type: 'list', path: 'steps', label: 'Steps', itemName: 'step', titleField: 'title', max: 6,
            blank: { title: '', text: '' }, fields: [text('title', 'Title'), area('text', 'Text')],
          },
        ],
      },
      {
        id: 'apply',
        title: 'Application form',
        description: 'Applications arrive in Admin → Partners → Applications, and the team gets an email for each one.',
        fields: [
          toggle('apply.enabled', 'Show the “Become a partner” form'),
          text('apply.title', 'Heading'),
          area('apply.lead', 'Introduction'),
          strings('apply.types', 'Types of partnership to choose from', { max: 10 }),
          text('apply.button', 'Button'),
        ],
      },
      {
        id: 'menu',
        title: 'Menu',
        description: '“Our partners” is also listed under About in the main menu and in the footer, which are edited with the other menus.',
        fields: [toggle('showInMenu', 'Also show “Partners” as its own item in the main menu')],
      },
    ],
  },

  // ------------------------------------------------------------------ Projects
  {
    slug: 'projects',
    label: 'Projects page',
    icon: 'fa-briefcase',
    description: 'The wording on the Projects page and each project’s case study. The projects themselves are added under Projects in the admin menu.',
    publicPath: '/projects',
    sections: [
      {
        id: 'hero',
        title: 'Page heading',
        fields: [
          text('hero.eyebrow', 'Small label above the heading'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          image('hero.image', 'Banner photo', { hint: 'Shown darkened behind the heading. Remove it for the plain dark header.' }),
          text('hero.primaryLabel', 'Main button'),
          text('hero.secondaryLabel', 'Second button'),
        ],
      },
      {
        id: 'labels',
        title: 'Labels and messages',
        fields: [
          text('labels.all', 'Filter: all projects'),
          text('labels.search', 'Search box'),
          text('labels.featured', 'Featured project label'),
          text('labels.viewCase', 'Link on each project'),
          area('labels.empty', 'Shown before any project is published'),
          text('labels.noResults', 'Shown when a search finds nothing'),
          text('labels.statProjects', 'Number: projects'),
          text('labels.statClients', 'Number: organisations'),
          text('labels.statSectors', 'Number: sectors'),
          text('labels.statServices', 'Number: services'),
          text('labels.challenge', 'Case study: first section'),
          text('labels.solution', 'Case study: second section'),
          text('labels.outcome', 'Case study: third section'),
          text('labels.results', 'Case study: results heading'),
          text('labels.technologies', 'Case study: technologies heading'),
          text('labels.related', 'Case study: more projects heading'),
          text('labels.visit', 'Case study: live project button'),
        ],
      },
      {
        id: 'cta',
        title: 'Closing call to action',
        fields: [text('cta.title', 'Heading'), area('cta.text', 'Text'), text('cta.button', 'Button')],
      },
    ],
  },

  // ------------------------------------------------------------------ Learning hub
  {
    slug: 'learning',
    label: 'Learning hub',
    icon: 'fa-book-open-reader',
    description: 'The wording on the Learning pages and the names of the five levels. The fields, topics and notes are written under Learning in the admin menu.',
    publicPath: '/learning',
    sections: [
      {
        id: 'hero',
        title: 'Page heading',
        fields: [
          text('hero.eyebrow', 'Small label above the heading'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          image('hero.image', 'Banner photo', { hint: 'Shown darkened behind the heading. Remove it for the plain dark header.' }),
        ],
      },
      {
        id: 'levels',
        title: 'The five levels',
        description: 'Every field runs through these five stages, from complete beginner to expert. Keep them in this order.',
        fields: [
          text('howTitle', 'Heading'),
          area('howLead', 'Introduction'),
          {
            type: 'list', path: 'levels', label: 'Levels', itemName: 'level', titleField: 'name', max: 5,
            blank: { name: '', text: '' }, fields: [text('name', 'Name'), area('text', 'What it covers')],
          },
        ],
      },
      {
        id: 'servicesBand',
        title: 'On the Services page',
        description: 'A section on the Services page that introduces the Learning hub and lists its published fields.',
        fields: [
          toggle('servicesBand.show', 'Show the Learning hub section on the Services page'),
          text('servicesBand.eyebrow', 'Small label above the heading'),
          text('servicesBand.title', 'Heading'),
          area('servicesBand.text', 'Text'),
          text('servicesBand.button', 'Button'),
        ],
      },
      {
        id: 'kinds',
        title: 'Types of note',
        fields: [text('kinds.note', 'Note'), text('kinds.research', 'Research note'), text('kinds.lab', 'Hands-on lab'), text('kinds.cheatsheet', 'Cheat sheet')],
      },
      {
        id: 'labels',
        title: 'Labels and messages',
        fields: [
          text('labels.fieldsTitle', 'Fields heading'),
          text('labels.search', 'Search box'),
          area('labels.empty', 'Shown before any field is published'),
          text('labels.start', 'Button: start learning'),
          text('labels.continue', 'Button: continue'),
          text('labels.signIn', 'Invitation to sign in'),
          text('labels.markDone', 'Button: mark as complete'),
          text('labels.objectives', 'Note: objectives heading'),
          text('labels.resources', 'Note: resources heading'),
          area('labels.finished', 'Shown when a field is finished'),
        ],
      },
      {
        id: 'cta',
        title: 'Closing call to action',
        fields: [text('cta.title', 'Heading'), area('cta.text', 'Text'), text('cta.button', 'Button')],
      },
    ],
  },

  // ------------------------------------------------------------------ Blog
  {
    slug: 'blog',
    label: 'Blog page',
    icon: 'fa-pen-nib',
    description: 'The heading and wording around the blog. The articles and categories themselves are written under Blog in the admin menu.',
    publicPath: '/blog',
    sections: [
      {
        id: 'hero',
        title: 'Page heading',
        fields: [
          text('hero.eyebrow', 'Small label above the heading'),
          text('hero.title', 'Heading'),
          area('hero.lead', 'Introduction'),
          image('hero.image', 'Banner photo', { hint: 'Shown darkened behind the heading and search box. Remove it for the plain white header.' }),
        ],
      },
      {
        id: 'menu',
        title: 'Menu',
        fields: [
          toggle('showInMenu', 'Show “Blog” in the website’s main menu'),
          text('labels.menu', 'Menu label'),
        ],
      },
      {
        id: 'labels',
        title: 'Wording',
        description: 'Buttons and small headings on the blog and article pages.',
        fields: [
          text('labels.allPosts', '“All posts” filter'),
          text('labels.search', 'Search box placeholder'),
          text('labels.featured', 'Featured article label'),
          text('labels.loadMore', '“Load more” button'),
          text('labels.empty', 'Message when there are no articles'),
          text('labels.noResults', 'Message when a search finds nothing'),
          text('labels.onThisPage', 'Article contents heading'),
          text('labels.share', 'Share heading'),
          text('labels.related', 'Related articles heading'),
          text('labels.writtenBy', 'Author box label'),
          text('labels.newsletterTitle', 'Newsletter box heading'),
          area('labels.newsletterText', 'Newsletter box text'),
        ],
      },
    ],
  },

  // ------------------------------------------------------------------ Join and error pages
  {
    slug: 'other',
    label: 'Join & error pages',
    icon: 'fa-user-plus',
    description: 'The “Join ADRAM” page people see before creating an account, and the page-not-found and access-denied messages.',
    publicPath: '/join',
    sections: [
      {
        id: 'join',
        title: 'Join page',
        fields: [
          text('join.eyebrow', 'Small label'),
          text('join.titleTraining', 'Heading when enrolling in training'),
          area('join.leadTraining', 'Introduction when enrolling in training'),
          text('join.titleScholarship', 'Heading when opening a scholarship'),
          area('join.leadScholarship', 'Introduction when opening a scholarship'),
          text('join.targetLabel', 'Line above the scholarship name'),
          text('join.cardTitle', 'Card heading'),
          text('join.stepOne', 'Step 1'),
          text('join.stepTwo', 'Step 2'),
          text('join.stepTrainingLast', 'Step 3 (training)'),
          text('join.stepScholarshipLast', 'Step 3 (scholarship)'),
          text('join.createLabel', 'Button: create account'),
          text('join.signInLabel', 'Button: already have an account'),
          text('join.backLabel', 'Back link', { hint: 'Use {name} for the scholarship name (or “scholarships”).' }),
        ],
      },
      {
        id: 'why',
        title: 'Why join',
        fields: [
          text('join.whyEyebrow', 'Small label'),
          text('join.whyTitle', 'Heading'),
          {
            type: 'list',
            path: 'join.benefits',
            label: 'Benefits',
            itemName: 'benefit',
            titleField: 'title',
            max: 8,
            blank: { icon: 'award', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
        ],
      },
      {
        id: 'errors',
        title: 'Error pages',
        fields: [
          text('errors.notFoundTitle', 'Page not found: heading'),
          area('errors.notFoundText', 'Page not found: text'),
          text('errors.deniedTitle', 'Access denied: heading'),
          area('errors.deniedText', 'Access denied: text'),
          text('errors.homeLabel', 'Button: back to home'),
          text('errors.contactLabel', 'Button: contact us'),
        ],
      },
    ],
  },

  // ------------------------------------------------------------------ Sign in, register and password reset
  {
    slug: 'accounts',
    label: 'Sign-in & registration',
    icon: 'fa-right-to-bracket',
    description: 'The headings and side-panel stories on the sign-in, create-account and password-reset screens. The forms themselves, their labels and their security messages stay as they are.',
    publicPath: '/login',
    sections: [
      {
        id: 'shared',
        title: 'On every screen',
        fields: [
          text('shared.backLabel', 'Link back to the website'),
          text('shared.helpTitle', 'Help box: heading'),
          text('shared.helpEmailLabel', 'Help box: email link text'),
          text('shared.legal', 'Small print'),
          text('shared.legalLink', 'Small print: link text'),
        ],
      },
      {
        id: 'login',
        title: 'Sign in',
        fields: [
          text('login.title', 'Page heading'),
          area('login.subtitle', 'Text under the heading'),
          text('login.eyebrow', 'Side panel: small label'),
          text('login.heading', 'Side panel: heading'),
          area('login.text', 'Side panel: text'),
          {
            type: 'list',
            path: 'login.points',
            label: 'Side panel: points',
            itemName: 'point',
            titleField: 'title',
            max: 5,
            blank: { icon: 'shield', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
          text('login.switchText', 'Top-right prompt'),
          text('login.switchLabel', 'Top-right link text'),
        ],
      },
      {
        id: 'register',
        title: 'Create account',
        fields: [
          text('register.title', 'Page heading'),
          area('register.subtitle', 'Text under the heading'),
          text('register.eyebrow', 'Side panel: small label'),
          text('register.heading', 'Side panel: heading'),
          area('register.text', 'Side panel: text'),
          {
            type: 'list',
            path: 'register.points',
            label: 'Side panel: points',
            itemName: 'point',
            titleField: 'title',
            max: 5,
            blank: { icon: 'shield', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
          text('register.switchText', 'Top-right prompt'),
          text('register.switchLabel', 'Top-right link text'),
        ],
      },
      {
        id: 'forgot',
        title: 'Reset password',
        fields: [
          text('forgot.title', 'Page heading'),
          area('forgot.subtitle', 'Text under the heading'),
          text('forgot.eyebrow', 'Side panel: small label'),
          text('forgot.heading', 'Side panel: heading'),
          area('forgot.text', 'Side panel: text'),
          {
            type: 'list',
            path: 'forgot.points',
            label: 'Side panel: points',
            itemName: 'point',
            titleField: 'title',
            max: 5,
            blank: { icon: 'shield', title: '', text: '' },
            fields: [icon(), text('title', 'Title'), text('text', 'Text')],
          },
          text('forgot.switchText', 'Top-right prompt'),
          text('forgot.switchLabel', 'Top-right link text'),
        ],
      },
    ],
  },

  // ------------------------------------------------------------------ Interface wording
  {
    slug: 'interface',
    label: 'Interface wording (portal & admin)',
    icon: 'fa-language',
    description: 'Change fixed wording in the student portal, the admin dashboard and the sign-in forms: headings, buttons, hints and placeholders. Easiest way: press the “Edit text” button at the bottom left of any screen and click the wording you want to change. Everything you change is listed here.',
    publicPath: '/login',
    sections: [
      {
        id: 'items',
        title: 'Replaced wording',
        description: 'Each entry replaces every place that shows exactly the original text. Text that includes a name or a number (like “Hello, Amina”) changes for each person, so it cannot be matched.',
        fields: [
          {
            type: 'list',
            path: 'items',
            label: 'Replacements',
            itemName: 'replacement',
            titleField: 'from',
            max: 500,
            blank: { from: '', to: '' },
            fields: [text('from', 'Original text', { hint: 'Exactly as it appears on the screen.' }), area('to', 'Show instead')],
          },
        ],
      },
    ],
  },
];

// Pages with a video section (components/ui/VideoSection.jsx), and where on the page it appears.
const VIDEO_PAGES = {
  home: 'after “Why ADRAM”', about: 'after “Who we are”', services: 'after the list of services', courses: 'after the key numbers',
  scholarships: 'after “How we help”', learning: 'after the fields',
};
contentPages.forEach((p) => {
  if (!VIDEO_PAGES[p.slug]) return;
  p.sections.push({
    id: 'video',
    title: 'Video',
    description: `A video section shown ${VIDEO_PAGES[p.slug]}. It only appears when it is switched on and has a video.`,
    fields: [
      toggle('video.show', 'Show the video section'),
      { type: 'video', path: 'video.url', label: 'Video' },
      image('video.poster', 'Cover picture (optional)', { hint: 'Shown before the video plays. YouTube videos use their own thumbnail when this is empty.' }),
      text('video.eyebrow', 'Small label above the heading'),
      text('video.title', 'Heading'),
      area('video.text', 'Text'),
      { type: 'select', path: 'video.layout', label: 'Layout', options: [['right', 'Text on the left, video on the right'], ['left', 'Video on the left, text on the right'], ['wide', 'Heading on top, wide video below']] },
      text('video.buttonLabel', 'Button text (optional)', { placeholder: 'e.g. Start a project' }),
      link('video.buttonLink', 'Button link (optional)'),
    ],
  });
});

// Every public page also gets a "search and browser title" section (the tab title and the description search engines show).
const SEO_PAGES = ['home', 'about', 'team', 'services', 'courses', 'scholarships', 'contact', 'other', 'blog', 'partners', 'projects', 'learning'];
contentPages.forEach((p) => {
  if (!SEO_PAGES.includes(p.slug)) return;
  p.sections.push({
    id: 'seo',
    title: 'Search & browser title',
    description: 'The title shown on the browser tab and in Google results, and the short description under it. Link previews on WhatsApp and Facebook use the site-wide text and are not affected.',
    fields: [
      text('seo.title', 'Page title', { hint: 'About 60 characters. Use {name} for the company name.' }),
      area('seo.description', 'Description', { hint: 'About 150 characters: what this page offers, in one or two sentences.' }),
    ],
  });
});

export const contentPage = (slug) => contentPages.find((p) => p.slug === slug);

// Ready-made photos already on the website, offered next to the uploaded ones in the image picker.
const lib = (folder, group, names) => names.map((file) => ({ src: `/${folder}/${file}`, group, name: file.replace(/\.jpg$/, '') }));
export const SITE_LIBRARY = [
  ...lib('web', 'Web', ['hero-bg.jpg', 'heroimg-card.jpg', 'web2-md.jpg', 'webpic-md.jpg']),
  ...lib('mobile', 'Mobile', ['app1.jpg', 'app2.jpg', 'app3.jpg', 'app4.jpg', 'app5.jpg']),
  ...lib('software', 'Software', ['cardimg.jpg', 'soft1.jpg', 'soft2.jpg', 'soft3.jpg', 'soft4.jpg']),
  ...lib('network', 'Networking', ['net-card.jpg', 'net-hero.jpg', 'net-overview.jpg', 'net-aside.jpg']),
  ...lib('hardware', 'Hardware', ['hardware-card.jpg', 'hardware-hero.jpg', 'hardware-overview.jpg', 'hardware-aside.jpg']),
  ...lib('ai', 'AI', ['ai-card.jpg', 'ai-hero.jpg', 'ai-overview.jpg', 'ai-aside.jpg']),
  ...lib('analytics', 'Analytics', ['analytics-card.jpg', 'analytics-hero.jpg', 'analytics-overview.jpg', 'analytics-aside.jpg']),
  ...lib('consultancy', 'Consultancy', ['consult-card.jpg', 'consult-hero.jpg', 'consult-overview.jpg', 'consult-aside.jpg']),
  ...lib('transform', 'Transformation', ['transform-card.jpg', 'transform-hero.jpg', 'transform-overview.jpg', 'transform-aside.jpg']),
  ...lib('graphics', 'Graphics', ['graphics-card.jpg', 'graphics-hero.jpg', 'graphics-overview.jpg', 'graphics-aside.jpg']),
  ...lib('typing', 'Typing', ['typing-card.jpg', 'typing-hero.jpg', 'typing-overview.jpg', 'typing-aside.jpg']),
  ...lib('scholarship', 'Scholarships', ['scholarship-card.jpg', 'scholarship-hero.jpg', 'scholarship-help.jpg', 'scholarship-docs.jpg']),
];

// Logo names available for a service's tools: the SVG files in public/tech.
export const TECH_LOGOS = [
  'ai-api',
  'ai-automation',
  'ai-chatbot',
  'ai-dashboard',
  'ai-document',
  'ai-llm',
  'ai-ml',
  'an-clean',
  'an-forecast',
  'an-kpi',
  'an-report',
  'an-sheet',
  'an-sql',
  'an-stats',
  'an-survey',
  'an-warehouse',
  'android',
  'androidstudio',
  'angular',
  'apple',
  'aws',
  'bootstrap',
  'cs-assess',
  'cs-budget',
  'cs-policy',
  'cs-procure',
  'cs-project',
  'cs-risk',
  'cs-roadmap',
  'cs-tender',
  'cs-training',
  'cs-vendor',
  'css3',
  'dart',
  'django',
  'docker',
  'dt-change',
  'dt-cloud',
  'dt-code',
  'dt-docs',
  'dt-forms',
  'dt-mail',
  'dt-migrate',
  'dt-workflow',
  'expo',
  'express',
  'figma',
  'firebase',
  'flutter',
  'gd-banner',
  'gd-brand',
  'gd-camera',
  'gd-card',
  'gd-chart',
  'gd-logo',
  'gd-motion',
  'gd-portrait',
  'gd-poster',
  'gd-product',
  'gd-retouch',
  'gd-slides',
  'gd-social',
  'gd-ui',
  'gd-video',
  'git',
  'github',
  'googlecloud',
  'graphql',
  'html5',
  'hw-battery',
  'hw-chip',
  'hw-desktop',
  'hw-diag',
  'hw-fan',
  'hw-install',
  'hw-laptop',
  'hw-mouse',
  'hw-printer',
  'hw-ram',
  'hw-screen',
  'hw-ssd',
  'ionic',
  'java',
  'javascript',
  'jira',
  'kotlin',
  'laravel',
  'linux',
  'mongodb',
  'mysql',
  'net-backup',
  'net-cabling',
  'net-cctv',
  'net-fibre',
  'net-firewall',
  'net-folder',
  'net-lock',
  'net-monitor',
  'net-power',
  'net-remote',
  'net-router',
  'net-server',
  'net-switch',
  'net-vpn',
  'net-wifi',
  'nextjs',
  'nginx',
  'nodejs',
  'php',
  'postgresql',
  'postman',
  'python',
  'react',
  'redis',
  'spring',
  'sqlite',
  'swift',
  'tailwindcss',
  'ty-cert',
  'ty-cv',
  'ty-doc',
  'ty-fast',
  'ty-finger',
  'ty-format',
  'ty-game',
  'ty-group',
  'ty-home',
  'ty-keys',
  'ty-kids',
  'ty-posture',
  'ty-proof',
  'ty-test',
  'typescript',
  'vuejs',
  'wordpress',
  'xcode',
];
