# Generated by Django 6.1.1 on 2026-10-05 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Show the chat button on the website.')),
                ('name', models.CharField(default='ADRAM Assistant', max_length=60)),
                ('greeting', models.CharField(default='Hi! I’m the ADRAM Assistant. Ask me about our services, training programmes or scholarships.', max_length=300)),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='Questions offered to visitors before they type.')),
                ('instructions', models.TextField(blank=True, help_text='Extra rules for the assistant, e.g. topics to avoid.', max_length=4000)),
                ('knowledge', models.TextField(blank=True, help_text='Extra facts and FAQs the assistant should know.', max_length=20000)),
                ('model', models.CharField(choices=[('claude-haiku-4-5-20251001', 'Claude Haiku 4.5 (fast, lowest cost)'), ('claude-sonnet-5-5', 'Claude Sonnet 5.5 (more capable, higher cost)')], default='claude-haiku-4-5-20251001', max_length=60)),
                ('per_hour', models.PositiveSmallIntegerField(default=20, help_text='Messages one visitor can send per hour.')),
                ('per_conversation', models.PositiveSmallIntegerField(default=40, help_text='Messages in one conversation.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'chatbot settings',
                'verbose_name_plural': 'chatbot settings',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor', models.CharField(blank=True, help_text='A one-way fingerprint of the visitor’s network address.', max_length=64)),
                ('page', models.CharField(blank=True, help_text='Where the conversation started.', max_length=300)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('handoff', models.BooleanField(default=False, help_text='The visitor was pointed to a person.')),
                ('rating', models.SmallIntegerField(blank=True, help_text='1 = helpful, -1 = not helpful.', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Visitor'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(max_length=8000)),
                ('failed', models.BooleanField(default=False)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
