# Generated by Django 6.1.1 on 2026-10-05 13:08

from django.db import migrations, models


def seed(apps, schema_editor):
    from chatbot.faqs import DEFAULT_FAQS
    apps.get_model('chatbot', 'ChatbotSettings').objects.filter(faqs=[]).update(faqs=DEFAULT_FAQS)


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='Ready-made questions and answers (see chatbot/faqs.py).'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
