# Generated by Django 6.1.1 on 2026-10-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('partnership_type', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='new', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Private notes for the team.', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.CharField(blank=True, help_text='An uploaded image (/media/...) or a full https:// address.', max_length=500)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, help_text='One or two sentences about the partnership.', max_length=400)),
                ('featured', models.BooleanField(default=False, help_text='Shown in the spotlight with its quote.')),
                ('quote', models.TextField(blank=True, max_length=600)),
                ('quote_author', models.CharField(blank=True, max_length=120)),
                ('quote_role', models.CharField(blank=True, max_length=120)),
                ('since', models.PositiveIntegerField(blank=True, help_text='The year the partnership started.', null=True)),
                ('visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partners.partnergroup')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
