# Generated by Django 6.1.1 on 2026-10-03 04:36

import django.db.models.deletion
import newsletter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Show the sign-up form in the website footer.')),
                ('heading', models.CharField(default='Subscribe to our newsletter', max_length=80)),
                ('text', models.CharField(default='News about our services, new training programmes and scholarship opportunities. No spam, unsubscribe at any time.', max_length=240)),
                ('button_label', models.CharField(default='Subscribe', max_length=30)),
                ('placeholder', models.CharField(default='Your email address', max_length=60)),
                ('double_opt_in', models.BooleanField(default=True, help_text='Ask new subscribers to confirm their email address first.')),
                ('welcome_email', models.BooleanField(default=True, help_text='Send a short welcome email once someone is subscribed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'newsletter settings',
                'verbose_name_plural': 'newsletter settings',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Waiting for confirmation'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='pending', max_length=12)),
                ('source', models.CharField(choices=[('footer', 'Website footer'), ('admin', 'Added by an administrator'), ('import', 'Imported')], default='footer', max_length=10)),
                ('token', models.CharField(default=newsletter.models.new_token, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('preheader', models.CharField(blank=True, help_text='The grey preview line in the inbox.', max_length=150)),
                ('title', models.CharField(blank=True, help_text='The heading inside the email (defaults to the subject).', max_length=150)),
                ('body', models.TextField(help_text='Paragraphs separated by a blank line.', max_length=10000)),
                ('image', models.CharField(blank=True, help_text='A picture at the top (https:// or a site image).', max_length=500)),
                ('button_label', models.CharField(blank=True, max_length=60)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newsletter.issue')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newsletter.subscriber')),
            ],
            options={
                'unique_together': {('issue', 'subscriber')},
            },
        ),
    ]
