# Generated by Django 6.1.1 on 2026-10-04 14:02

import django.db.models.deletion
import team.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The page address: /team/<slug>.', max_length=80, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Empty = the account name.', max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(blank=True, help_text='One sentence under the name.', max_length=220)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True, help_text='The full introduction (simple formatting allowed).', max_length=8000)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=40)),
                ('cv_file', models.FileField(blank=True, storage=team.models._private_storage, upload_to=team.models.cv_upload_to)),
                ('cv_name', models.CharField(blank=True, max_length=200)),
                ('cv_visibility', models.CharField(choices=[('public', 'Everyone'), ('members', 'Signed-in users only'), ('hidden', 'Nobody (hidden)')], default='public', max_length=10)),
                ('generated_cv', models.BooleanField(default=True, help_text='Offer the printable CV made from this profile.')),
                ('allow_chat', models.BooleanField(default=True, help_text='Signed-in users can message this person.')),
                ('is_published', models.BooleanField(default=False, help_text='Shown on the Team page.')),
                ('featured', models.BooleanField(default=False, help_text='Shown first, in a larger card.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-featured', 'sort_order', 'id'],
            },
        ),
    ]
